main/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import handler404, handler500
from django.contrib.auth import views as auth_views

###### Importes para subir imagenes #####
from django.conf import settings
from django.conf.urls.static import static
#########################################

from main.views import inicio, inicioAdmin, logout_user, nosotros, soporte_ayuda, Error404, Error500

# handler404= Error_404.as_view()s

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', inicio, name='inicio'),
    # path('loggein/', loggedIn, name='inicio-sesion'),
    path('logout/',logout_user,name='logout'),
    path('adm/', inicioAdmin, name='inicio-admin'),
    #path('login/', login.as_view(), name="login"),
    path('login/', auth_views.LoginView.as_view(), name="login"),
    path('reset_password/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('reset_password_send/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset_password_complete', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    path('nosotros/', nosotros, name='nosotros'),
    path('', include('articulos.urls')),
    path('', include('usuarios.urls')),
    path('', include('inventario.urls')),
    path('', include('facturacion.urls')),
    path('', include('django.contrib.auth.urls')),
    #path("select2/", include('django_select2.urls')),
    path('soporte-ayuda/', soporte_ayuda, name="soporte_ayuda"),
]

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

handler404= Error404.as_view()

handler500 = Error500.as_error_view()

usuarios/urls.py
from django.urls import path

from usuarios.views import ImprimirOrdenServicio, cerrar_orden_servicio, ciudades, clientes, departamentos, editar_ciudad, editar_cliente, editar_departamento, editar_empleado, editar_empresa, editar_servicio, editar_sucursal, editar_vehiculo, editar_vehiculo_taller, eliminar_ciudad, eliminar_cliente, eliminar_departamento, eliminar_empleado, eliminar_orden_ser, eliminar_servicio, eliminar_sucursal, eliminar_vehiculo, empleado, empresa, historial_ord_servicio, ingresar_vehiculo_taller, ordenes_servicio, quitar_art_rel_ord_art, registrar_cliente, registrar_empleado, registrar_empresa, registrar_vehiculo, sacar_vehiculo_taller, servicios, sucursales, tbl_rel_orden_ser_art_hist, tbl_rel_orden_ser_articulos, vehiculos, vehiculos_taller


urlpatterns = [
    path('tu-empresa/', empresa, name='empresa'),
    path('tu-empresa/registrar/', registrar_empresa, name='registrar_empresa'),
    path('tu-empresa/editar/<int:pk>/', editar_empresa, name='editar_empresa'),
    path('sucursales/', sucursales, name='sucursales'),
    path('sucursales/editar/<int:pk>/', editar_sucursal, name='editar_sucursal'),
    path('sucursales/eliminar/<int:pk>/', eliminar_sucursal, name='eliminar_sucursal'),
    path('clientes/', clientes, name='clientes'),
    path('clientes/crear/', registrar_cliente, name='registrar_cliente'),
    path('clientes/editar/<int:pk>/', editar_cliente, name='editar_cliente'),
    path('clientes/eliminar/<int:pk>/', eliminar_cliente, name='eliminar_cliente'),
    path('extras/ciudades-municipios/', ciudades, name='ciudades'),
    path('extras/ciudades-municipios/editar/<int:pk>/', editar_ciudad, name='editar_ciudad'),
    path('extras/ciudades-municipios/eliminar/<int:pk>/', eliminar_ciudad, name='eliminar_ciudad'),
    path('extras/departamentos/', departamentos, name='departamentos'),
    path('extras/departamentos/editar/<int:pk>/', editar_departamento, name='editar_departamento'),
    path('extras/departamentos/eliminar/<int:pk>/', eliminar_departamento, name='eliminar_departamento'),
    path('vehiculos/', vehiculos, name='vehiculos'),
    path('vehiculos/crear/', registrar_vehiculo, name='registrar_vehiculo'),
    path('vehiculos/editar/<int:pk>/', editar_vehiculo, name='editar_vehiculo'),
    path('vehiculos/eliminar/<int:pk>/', eliminar_vehiculo, name='eliminar_vehiculo'),
    path('vehiculos/en-taller/', vehiculos_taller, name='vehiculos_taller'),
    path('vehiculos/en-taller/editar/<int:pk>/', editar_vehiculo_taller, name='editar_vehiculo_taller'),
    path('vehiculos/en-taller/sacar/<int:pk>/', sacar_vehiculo_taller, name='sacar_vehiculo_taller'),
    path('vehiculos/ingresar-al-taller//<int:pk>/', ingresar_vehiculo_taller, name='ingresar_vehiculo_taller'),
    path('empleados/', empleado, name='empleados'),
    path('empleados/crear/', registrar_empleado, name= 'registrar_empleado'),
    path('empleados/editar/<int:pk>/', editar_empleado, name='editar_empleado'),
    path('empleados/eliminar/<int:pk>/', eliminar_empleado, name='eliminar_empleado'),
    path('ordenes-de-servicio/', ordenes_servicio, name='ordenes_servicio'),
    path('ordenes-de-servicio/articulos/<int:pk>/', tbl_rel_orden_ser_articulos, name='detalle_orden_servicio'),
    path('quitar-articulo-orden-compra/<int:pk>/', quitar_art_rel_ord_art, name="quitar_art_rel_ord_art"),
    path('ordenes-de-servicio/cerrar/<int:pk>/', cerrar_orden_servicio, name='cerrar_orden_servicio'),
    path('ordenes-de-servicio/historial/', historial_ord_servicio, name='historial_ord_servicio'),
    path('ordenes-de-servicio/historial/detalles/<int:pk>/', tbl_rel_orden_ser_art_hist, name='tbl_rel_orden_ser_art_hist'),
    path('ordenes-de-servicio/historial/eliminar/<int:pk>/', eliminar_orden_ser, name='eliminar_orden_ser'),
    path('ordenes-de-servicio/imprimir/<int:pk>/', ImprimirOrdenServicio.as_view(), name='imprimir_factura_venta'),
    path('servicios/', servicios, name='servicios'),
    path('servicios/editar/<int:pk>/', editar_servicio, name='editar_servicio'),
    path('servicios/eliminar/<int:pk>/', eliminar_servicio, name='eliminar_servicio'),
]

usuarios/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _
from django.contrib.auth.models import User

from articulos.models import Articulos, Marcas

# Create your models here.

class Departamentos(models.Model):
    id_depart = models.CharField(max_length=10, verbose_name="Código nacional:")
    dep_nombre = models.CharField(max_length=45, verbose_name="Nombre:")
    class Estado(models.TextChoices):
        ACTIVO = '1', _('Activo')
        INACTIVO = '0', _('Inactivo')
    dep_estado = models.CharField(max_length=1, choices=Estado.choices, default=Estado.ACTIVO, verbose_name="Estado:")
    def __str__(self) -> str:
        return "%s" % (self.dep_nombre)


class Ciudades(models.Model):
    id_ciudad = models.CharField(max_length=10, verbose_name="Código nacional_")
    ciu_nombre = models.CharField(max_length=45, verbose_name="Nombre:")
    tbl_departamento_iddepart = models.ForeignKey(
        Departamentos, on_delete=models.CASCADE, verbose_name="Departamento:")
    class Estado(models.TextChoices):
        ACTIVO = '1', _('Activo')
        INACTIVO = '0', _('Inactivo')
    ciu_estado = models.CharField(
        max_length=1, choices=Estado.choices, default=Estado.ACTIVO, verbose_name="Estado:")

    def __str__(self) -> str:
        return "%s - %s" % (self.ciu_nombre, self.tbl_departamento_iddepart)


class Empresa(models.Model):
    empr_nombre = models.CharField(max_length=80, verbose_name="Nombre:")
    empr_nit = models.CharField(max_length=20, verbose_name="Nit:")
    empr_dueno = models.CharField(max_length=80, verbose_name="Dueño:")
    empr_sitio_web = models.CharField(max_length=100, verbose_name="Sitio Web:")
    empr_razon_social = models.TextField(max_length=300, verbose_name="Razón Social:")
    class Estado(models.TextChoices):
        ACTIVO = '1', _('Activo')
        INACTIVO = '0', _('Inactivo')
    empr_estado = models.CharField(max_length=1, choices=Estado.choices, default=Estado.ACTIVO, verbose_name="Estado:")
    empr_foto = models.ImageField(upload_to='images/empresa', blank=True, default='images/empresa/default.png', verbose_name = "Foto:")
    
    def __str__(self) -> str:
        return "%s" % (self.empr_nombre)

class Sucursales(models.Model):
    tbl_ciudad_idciudad = models.ForeignKey(Ciudades, on_delete=models. CASCADE, verbose_name="Ciudades:")
    tbl_empresas_idempresa = models.ForeignKey(Empresa, on_delete=models. CASCADE, verbose_name="Empresa:")
    suc_nombre = models.CharField(max_length=80, verbose_name="Nombre:")
    suc_administrador = models.CharField(max_length=80, verbose_name="Administrador:")
    suc_direccion = models.CharField(max_length=80, verbose_name="Dirección:")
    class Tipo(models.TextChoices):
        PRINCIPAL = '1', _('Principal')
        SEDE = '0', _('Sede')
    suc_tipo = models.CharField(max_length=1, choices=Tipo.choices, default=Tipo.SEDE, verbose_name="Tipo:")
    suc_telefono = models.CharField(max_length=20, verbose_name="Teléfono:")
    suc_celular = models.CharField(max_length=20, verbose_name="Celular:")
    suc_email = models.CharField(max_length=100, verbose_name="E-mail:")
    class Estado(models.TextChoices):
        ACTIVO = '1', _('Activo')
        INACTIVO = '0', _('Inactivo')
    suc_estado = models.CharField(max_length=1, choices=Estado.choices, default=Estado.ACTIVO, verbose_name="Estado:")

    def __str__(self) -> str:
        return "%s" % (self.suc_nombre)

class Servicios(models.Model):
    tbl_sucursales_idsucursal = models.ForeignKey(Sucursales, on_delete=models.CASCADE, verbose_name="Sucursal:")
    ser_nombre = models.CharField(max_length=50, verbose_name="Nombre:")
    ser_descripcion = models.TextField(max_length=200, verbose_name="Descripción:")
    class Estado(models.TextChoices):
        ACTIVO = '1', _('Activo')
        INACTIVO = '0', _('Inactivo')
    ser_estado = models.CharField(max_length=1, choices=Estado.choices, default=Estado.ACTIVO,  verbose_name="Estado:")

    def __str__(self) -> str:
        return "%s" % (self.ser_nombre)

class Empleados(models.Model):
    tbl_sucursal_idsucursal = models.ForeignKey(Sucursales, on_delete=models. CASCADE, verbose_name="Sucursal:")
    id_emp_identificacion = models.CharField(max_length=50, unique=True, verbose_name="Identificación:")
    class TipoDocumento(models.TextChoices): 
        TI = 'T.I', _('Tarjeta de Identidad')
        CC = 'C.C', _('Cédula de Ciudadanía')
        CE = 'C.E', _('Cédula de Extranjería')
        Pas = 'Pas', _('Pasaporte')
    emp_tipo_documento = models.CharField(max_length=3, choices=TipoDocumento.choices, default=TipoDocumento.CC, verbose_name="Tipo de documento:")
    tbl_ciudad_idciudad = models.ForeignKey(Ciudades, on_delete=models. CASCADE, verbose_name="Ciudades:")
    emp_nombre = models.CharField(max_length=50, verbose_name="Nombres:")
    emp_apellidos = models.CharField(max_length=50, verbose_name="Apellidos:")
    class Genero(models.TextChoices):
        FEMENINO = 'F', _('Femenino')
        MASCULINO = 'M', _('Masculino')
    emp_genero = models.CharField(max_length=1, choices=Genero.choices, verbose_name="Género:")
    emp_direccion = models.CharField(max_length=100, verbose_name="Dirección:")
    emp_telefono = models.CharField(max_length=20, verbose_name="Teléfono:")
    emp_celular = models.CharField(max_length=20, verbose_name="Celular:")
    emp_email = models.EmailField(max_length=100, unique=True, verbose_name="E-mail:")
    emp_fecha_nacimiento = models.DateField( verbose_name="Fecha de nacimiento:")
    emp_cargo = models.CharField(max_length=50, verbose_name="Cargo:")
    emp_num_contrato = models.CharField(max_length=50, verbose_name="Número de Contrato:")
    emp_fecha_ingreso = models.DateField( verbose_name="Fecha de ingreso:")
    class Estado(models.TextChoices):
        ACTIVO = '1', _('Activo')
        INACTIVO = '0', _('Inactivo')
    emp_estado = models.CharField(max_length=1, choices=Estado.choices, default=Estado.ACTIVO, verbose_name="Estado")
    emp_foto = models.ImageField(upload_to='images/usuarios', blank=True, default='images/usuarios/default.png', verbose_name = "Foto:")
    user = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, default=None)

    def __str__(self) -> str:
        return "%s - %s" % (self.emp_nombre, self.emp_apellidos)

class Cliente(models.Model):
    id_identificacion = models.CharField(max_length=50, unique=True, verbose_name="Identificación:")
    class TipoDocumento(models.TextChoices):
        TI = 'T.I', _('Tarjeta de Identidad')
        CC = 'C.C', _('Cédula de Ciudadanía')
        CE = 'C.E', _('Cédula de Extranjería')
        Pas = 'Pas', _('Pasaporte')
    cli_tipo_documento = models.CharField(max_length=3, choices=TipoDocumento.choices, default=TipoDocumento.CC, verbose_name="Tipo de documento:")
    cli_nombres = models.CharField(max_length=50, verbose_name="Nombres:")
    cli_apellidos = models.CharField(max_length=50, verbose_name="Apellidos:")
    class Genero(models.TextChoices):
        FEMENINO = 'F', _('Femenino')
        MASCULINO = 'M', _('Masculino')
    cli_genero = models.CharField(max_length=2, choices=Genero.choices, verbose_name="Género:")
    cli_direccion = models.CharField(max_length=100, verbose_name="Dirección:")
    tbl_ciudades_idciudad = models.ForeignKey(Ciudades, on_delete=models.CASCADE, verbose_name="Ciudad")
    cli_telefono = models.CharField(max_length=20, blank=True, verbose_name="Teléfono:")
    cli_celular = models.CharField(max_length=20, verbose_name="Celular")
    cli_email = models.EmailField(max_length=100, verbose_name="Email")
    class Estado(models.TextChoices):
        ACTIVO = '1', _('Activo')
        INACTIVO = '0', _('Inactivo')
    cli_estado = models.CharField(max_length=1, choices=Estado.choices, default=Estado.ACTIVO, verbose_name="Estado")

    def __str__(self) -> str:
        return "%s - %s" % (self.cli_nombres, self.cli_apellidos)

class Vehiculo(models.Model):
    id_matricula = models.CharField(unique=True, max_length=6, verbose_name="Matrícula:")
    tbl_cliente_ididentificacion = models.ForeignKey(Cliente, on_delete=models.CASCADE, verbose_name="Dueño:")
    veh_modelo = models.CharField(max_length=45, verbose_name="Modelo:")
    veh_color = models.CharField(max_length=20, verbose_name="Color:")
    tbl_marcas_idmarca = models.ForeignKey(Marcas, on_delete=models.CASCADE, verbose_name="Marca:")
    veh_version = models.CharField(max_length=20, verbose_name="Versión:")
    veh_anio = models.CharField(max_length=4, verbose_name="Año:")  # preguntas
    veh_chasis_vin = models.CharField(max_length=45, verbose_name="Chasis_VIN:")
    veh_motor = models.CharField(max_length=45, verbose_name="Motor:")
    veh_ultima_fecha_ingreso = models.DateField(verbose_name="Última fecha de ingreso:")
    veh_ultima_fecha_salida = models.DateField(blank=True, null=True, verbose_name="Última fecha de salida:")
    veh_informe_tecnico = models.TextField(max_length=500, verbose_name="Informe técnico:")
    class Estado(models.TextChoices):
        ACTIVO = '1', _('Activo')
        INACTIVO = '0', _('Inactivo')
    veh_estado = models.CharField(
        max_length=1, choices=Estado.choices, default=Estado.ACTIVO, verbose_name="Estado")
    class EnTaller(models.TextChoices):
        EN_TALLER = 'Si', _('En taller')
        ENTREGADO = 'No', _('Entregado')
    veh_taller = models.CharField(max_length=2, choices=EnTaller.choices, default=EnTaller.EN_TALLER, verbose_name="Proceso:")

    def __str__(self) -> str:
        return "%s" % (self.id_matricula)

class TblRelServiciosEmpleados(models.Model):
    tbl_empleados_idempleado = models.ForeignKey(Empleados, on_delete=models.CASCADE, verbose_name="Empleado:")
    tbl_servicios_idservicio = models.ForeignKey(Servicios, on_delete=models.CASCADE, verbose_name="Servicios:")

class TblRelClienteServicios(models.Model):
    tbl_cliente_ididentificacion=models.ForeignKey(Cliente, on_delete=models.CASCADE, verbose_name="Cliente:")

main/views.py
from multiprocessing import context
from django.shortcuts import render, redirect
from django.views.defaults import page_not_found
from django.contrib import messages
from django.views.generic import View, TemplateView, ListView, DetailView
from django.contrib.auth.decorators import login_required
from django.contrib.auth import logout
from articulos.models import Articulos, Categoria, Marcas, Proveedores
from inventario.models import Pedidos
from usuarios.models import Ciudades, Cliente, Departamentos, Empleados, OrdenServicio, Servicios, Sucursales, Vehiculo

#from clientes.models import Cliente, Ciudades, Departamentos, Vehiculo

def inicio(request):
    context = {

    }
    return render(request, 'index.html', context)

def nosotros(request):
    titulo = "Nosotros"
    context = {
        'titulo': titulo
    }
    return render(request, 'nosotros.html', context)

def soporte_ayuda(request):
    titulo = "Soporte y ayuda"
    context = {
        'titulo': titulo
    }
    return render(request, 'interfaz_soporte_ayuda.html', context)

def logout_user(request):
    logout(request)
    return redirect('inicio')


@login_required(login_url='login')
def inicioAdmin(request):
    titulo = "Panel Principal"
    context = {
        'titulo': titulo
    }
    return render(request, 'frm_inicio_app.html', context)

# def error_404(request, exception):
#     return page_not_found(request, 'error_404.html')

# class Error_404(TemplateView):
#     template_name = "error_404.html"

class Error404(TemplateView):
    template_name = "error_404.html"

class Error500(TemplateView):
    template_name = "error_500.html"

    @classmethod
    def as_error_view(cls):
        v = cls.as_view()
        def view(request):
            r = v(request)
            r.render()
            return r
        return view

main/templates/usuarios/frm_empresa.html
{% extends 'partials/bodyApp.html' %}
{% load crispy_forms_tags %}
{% load static %}


{% block css %}
<link rel="stylesheet" href="{% static 'css/frm_empresa.css' %}">
{% endblock css %}
    

{% block contenido %}
<section>
        <div class="titulo_superior">
            <h1>Registra tu empresa aquí</h1>
        </div>
        <form action="" method="POST" enctype="multipart/form-data">
            {{form|crispy}}
            {% csrf_token %}
            <img src="{% static 'img/registrar_empresa.svg' %}" alt="Ilustración a gestionar empresa" id="img1">
            <div class="frame_b">
                <button type="submit" value="Guardar" id="btn_guardar">Guardar</button>
                <button type="reset" value="Cacelar" id="btn_cancelar">Cancelar</button>
            </div>
        </form>
</section>
{% endblock contenido %}
    

main/templates/usuarios/frm_registrar_nuevo_vehiculo.html
{% extends 'partials/bodyApp.html' %}
{% load crispy_forms_tags %}
{% load static %}


{% block css %}
<link rel="stylesheet" href="{% static 'css/frm_registrar_vehiculo.css' %}">
{% endblock css %}
    


{% block contenido %}
<section>
    <div class="titulo">
        <h1>Registrar nuevo vehículo</h1>
    </div>

    <form action="" method="POST">
        <img src="{% static 'img/registrar_vehiculos.svg' %}" alt="Icono añadir proveedor" id="icono_add_proveedor">
        {{form|crispy}}
        {% csrf_token %}
        <div class="frame_b">
            <button type="submit" value="Guardar" id="btn_guardar">Guardar</button>
            <button type="reset" value="Cancelar" id="btn_cancelar">Cancelar</button>
        </div>
    </form>
</section>
{% endblock contenido %}


{% block js %}
<script>
    $(function () {
        $("#sidebarToggle").click();
        $("#id_tbl_cliente_ididentificacion").select2({
            placeholder:"Selecciona un cliente",
            allowClear:true,
            width:"100%",
        });
        $("#id_tbl_marcas_idmarca").select2({
            placeholder:"Selecciona una marca",
            allowClear:true,
            width:"100%",
        });
    });
</script>
{% endblock js %}
    

main/templates/usuarios/interfaz_ciu_municipios.html
{% extends 'partials/bodyApp.html' %}
{% load crispy_forms_tags %}
{% load static %}


{% block css %}
<link rel="stylesheet" href="{% static 'css/interfaz_ciu_municipios.css' %}">
{% endblock css %}


{% block contenido %}
<section>
    <div class="titulo_superior">
        <h2>Ciudades y municipios guardados</h2>
    </div>
    <div class="contenedor_form">
        <form method="GET">
            <label for="CiuBusqueda" class="label_buscar">Buscar ciudad:</label>
            <input type="search" name="ciu_busqueda" id="CiuBusqueda" value="{{request.GET.ciu_busqueda}}" placeholder="Buscar">
    
            <button type="submit" id="btn_mostrar_filtro" class="btn btn-outline-success"><i class="bi bi-search"></i></button>
        </form>
    </div>
    <div class="contenedor_tabla">
        <table>
            <thead>
                <tr>
                    <th>Código Nacional:</th>
                    <th>Ciudad o municipio</th>
                    <th>Departamento</th>
                    {% if perms.usuarios.delete_ciudades or perms.usuarios.change_ciudades %}
                    <th>Acciones</th>
                    {% endif %}
                </tr>
                </tr>
            </thead>
            <tbody>

                {% for ciudad in ciudades %}
                <tr>
                    
                        <td>{{ciudad.id_ciudad}}</td>
                        <td>{{ciudad.ciu_nombre}}</td>
                        <td>{{ciudad.tbl_departamento_iddepart}}</td>
                        {% if perms.usuarios.delete_ciudades or perms.usuarios.change_ciudades %}
                        <td>
                            
                            {% if perms.usuarios.change_ciudades %}
                            <a href="{% url 'editar_ciudad' ciudad.pk %}">
                                <img src="{% static 'img/editar.svg' %}" alt="Botón editar" id="btn_editar" title="Editar ciudad">
                            </a>
                            {% endif %}

                            {% if perms.usuarios.delete_ciudades %}                           
                            <a href="#" onclick="eliminar_registros({{ ciudad.pk }})">
                                <img src="{% static 'img/eliminar.svg' %}" alt="Botón editar" id="btn_eliminar" title="Mover a papelera">
                            </a>
                            {% endif %}

                        </td>
                        {% endif %}
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
    <img src="{% static 'img/ilustracion_ciudades.svg' %}" alt="Ilustración relativa a ciudades" id="img1">
    
    {% if perms.usuarios.add_ciudades %}
    <a href="#" id="btn_anadir" title="Añadir nueva ciudad">Añadir</a>
    {% endif %}
</section>    
<section class="modal-form ">
    <div class="container_modal-form">
        <div class="container_h2-form">
            <h2>Añadir nueva ciudad o municipio</h2>
            <a href="#" class="modal_close-form container_cerrar-form">
                <img src="{% static 'img/cerrar.svg' %}" alt="">
            </a>
        </div>
        <img src="{% static 'img/ilustracion_ciudades.svg' %}" alt="Imagen ilustrativa a ciudades" id="img2">
        {% if perms.usuarios.add_ciudades %}
        <form action="" method="POST">
            {{form|crispy}}
            {% csrf_token %}
            <div class="frame_b">
                <button type="submit" value="Guardar" id="btn_guardar">Guardar</button>
                <button type="reset" value="Cacelar" id="btn_cancelar">Cancelar</button>
            </div>
        </form>
        {% endif %}
    </div>
</section>
{% endblock contenido %}


{% block js %}
<script>
    $(function () {
        $("#sidebarToggle").click();
        $("#id_tbl_departamento_iddepart").select2({
            placeholder:"Selecciona un departamento",
            allowClear:true,
            width:"100%",
        });
    });
</script>
<script src="{% static 'js/interfaz_ciu_municipios.js' %}"></script>
{% endblock js %}

main/templates/usuarios/interfaz_departamentos.html
{% extends 'partials/bodyApp.html' %}
{% load crispy_forms_tags %}
{% load static %}


{% block css %}
<link rel="stylesheet" href="{% static 'css/interfaz_departamentos.css' %}">
{% endblock css %}


{% block contenido %}
<section>
    <div class="titulo_superior">
        <h2>Departamentos guardados</h2>
    </div>
    <div class="contenedor_form">
        <form method="GET">
            <label for="DepBusqueda" class="label_buscar">Buscar depatamento:</label>
            <input type="search" name="dep_busqueda" id="DepBusqueda" value="{{request.GET.dep_busqueda}}" placeholder="Buscar">
    
            <button type="submit" id="btn_mostrar_filtro" class="btn btn-outline-success"><i class="bi bi-search"></i></button>
        </form>
    </div>
    <div class="contenedor_tabla">
        <table>
            <thead>
                <tr>
                    <th>Código nacional</th>
                    <th>Departamento</th>
                    
                    {% if perms.usuarios.change_departamentos or perms.usuarios.delete_departamentos %}
                    <th>Acciones</th>
                    {% endif %}
                </tr>
            </thead>
            <tbody>

                {% for depart in departamentos %}
                <tr>
                    <td>{{depart.id_depart}}</td>
                    <td>{{depart.dep_nombre}}</td>
                    {% if perms.usuarios.change_departamentos or perms.usuarios.delete_departamentos %}
                    <td>
                        
                        {% if perms.usuarios.change_departamentos %}                             
                        <a href="{% url 'editar_departamento' depart.pk %}">
                            <img src="{% static 'img/editar.svg' %}" alt="Botón editar" id="btn_editar" title="Editar departamento">
                        </a>
                        {% endif %}
                        
                        {% if perms.usuarios.delete_departamentos %}                            
                        <a href="#" onclick="eliminar_registros({{ depart.pk }})">
                            <img src="{% static 'img/eliminar.svg' %}" alt="Botón editar" class="btn_eliminar" title="Mover a papelera">
                        </a>
                        {% endif %}
                    </td>
                    {% endif %}
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
    <img src="{% static 'img/ilustracion_departamentos.svg' %}" alt="Ilustración relaacionada a departamentos"
        id="img1">
    
    {% if perms.usuarios.add_departamentos %}
    <a href="#" id="btn_anadir" title="Añadir nuevo departamento">Añadir</a>
    {% endif %}
</section>
<section class="modal-form ">
    <div class="container_modal-form">
        <div class="container_h2-form">
            <h2>Añadir nuevo departamento</h2>
            <a href="#" class="modal_close-form container_cerrar-form">
                <img src="{% static 'img/cerrar.svg' %}" alt="">
            </a>
        </div>
        <img src="{% static 'img/ilustracion_departamentos.svg' %}" alt="Imagen ilustrativa a ciudades" id="img2">
        {% if perms.usuarios.add_departamentos %}
        <form action="" method="POST">
            {{form|crispy}}
            {% csrf_token %}
            <div class="frame_b">
                <button type="submit" value="Guardar" id="btn_guardar">Guardar</button>
                <button type="reset" value="Cacelar" id="btn_cancelar">Cancelar</button>
            </div>
        </form>
        {% endif %}
    </div>
</section>
{% endblock contenido %}


{% block js %}
<script src="{% static 'js/interfaz_departamentos.js' %}"></script>
{% endblock js %}