facturacion/urls.py
from django.urls import path

from facturacion.views import ImprimirFacturaVenta, cerrar_factura, eliminar_art_detalle_fac, eliminar_factura_venta, facturar_venta, detalle_fac_venta, historial_ventas, tbl_rel_factura_art_hist

urlpatterns = [
    path('facturar-venta/', facturar_venta, name='facturar_venta'),
    path('facturar-venta/detalles/<int:pk>/', detalle_fac_venta, name='detalle_fac_venta'),
    path('quitar-articulo-factura/<int:pk>/<int:tbl_facturas_idfactura>/', eliminar_art_detalle_fac, name="quitar_art_dell_fac"),
    path('facturar-venta/imprimir-factura/<int:pk>/', ImprimirFacturaVenta.as_view(), name='imprimir_factura_venta'),
    path('facturar-venta/cerrar/<int:pk>/', cerrar_factura, name='cerrar_factura'),
    path('facturar-venta/historial-ventas/', historial_ventas, name='historial_ventas'),
    path('facturar-venta/historial-ventas/detalles/<int:pk>/', tbl_rel_factura_art_hist, name='historial_detalle_factura'),
    path('facturar-venta/historial-ventas/eliminar/<int:pk>/', eliminar_factura_venta, name='eliminar_factura_venta')
]

main/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import handler404, handler500
from django.contrib.auth import views as auth_views

###### Importes para subir imagenes #####
from django.conf import settings
from django.conf.urls.static import static
#########################################

from main.views import inicio, inicioAdmin, logout_user, nosotros, soporte_ayuda, Error404, Error500

# handler404= Error_404.as_view()s

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', inicio, name='inicio'),
    # path('loggein/', loggedIn, name='inicio-sesion'),
    path('logout/',logout_user,name='logout'),
    path('adm/', inicioAdmin, name='inicio-admin'),
    #path('login/', login.as_view(), name="login"),
    path('login/', auth_views.LoginView.as_view(), name="login"),
    path('reset_password/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('reset_password_send/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset_password_complete', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    path('nosotros/', nosotros, name='nosotros'),
    path('', include('articulos.urls')),
    path('', include('usuarios.urls')),
    path('', include('inventario.urls')),
    path('', include('facturacion.urls')),
    path('', include('django.contrib.auth.urls')),
    #path("select2/", include('django_select2.urls')),
    path('soporte-ayuda/', soporte_ayuda, name="soporte_ayuda"),
]

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

handler404= Error404.as_view()

handler500 = Error500.as_error_view()

facturacion/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _
from articulos.models import Articulos

from usuarios.models import Cliente, Empleados, OrdenServicio

# Create your models here.

class FacturaVenta(models.Model):
    fac_numero_serie = models.AutoField(primary_key=True, verbose_name="Número de serie:", unique=True)
    tbl_ordenes_servicio_idorden_servicio = models.OneToOneField(OrdenServicio, on_delete=models.CASCADE, blank=True, null=True, verbose_name="Orden de servicio número:")
    tbl_empleados_idempleado = models.ForeignKey(Empleados, on_delete=models.CASCADE, verbose_name="Empleado:")
    tbl_clientes_idcliente = models.ForeignKey(Cliente, on_delete=models.CASCADE, verbose_name="Cliente:")
    fac_fecha = models.DateField(auto_now=True, verbose_name="Fecha:")
    fac_costo_servicio = models.DecimalField(max_digits=8, decimal_places=2, default=0, verbose_name="Costo del servicio:")
    fac_caja = models.CharField(max_length=10, verbose_name="Caja número:")
    fac_descuentos = models.DecimalField(max_digits=7, decimal_places=2, default=0, verbose_name="Descuento:")
    fac_total_pagar = models.DecimalField(max_digits=10, decimal_places=2, default=0, verbose_name="Total a pagar:")
    fac_observaciones = models.TextField(max_length=500, verbose_name="Observaciones:")
    class Estado(models.TextChoices):
        ACTIVO = '1', _('Activo')
        INACTIVO = '0', _('Inactivo')
        CERRADA = '2', _('Cerrada')
    fac_estado = models.CharField(max_length=1, choices=Estado.choices, default=Estado.ACTIVO,  verbose_name="Estado:")
    def _pagar_cliente(self):
        costo_ser = self.fac_costo_servicio
        costo_art = self.fac_total_pagar
        descuento = self.fac_descuentos
        total = (costo_ser + costo_art) - descuento
        return total
    fac_pagar_cliente = property(_pagar_cliente)

    # def _pagar(self):
    #     from django.db.models import Sum
    #     from facturacion.models import DetalleFacturaVenta

    #     articulos = DetalleFacturaVenta.objects.filter(
    #         tbl_facturas_idfactura = self
    #     ).aggregate(Sum('dep_total'))
        
    #     costo_art = articulos.get('dep_total__sum') if articulos.get('dep_total__sum') is not None else 0

    #     costo_ser = self.fac_costo_servicio

    #     descuento = self.fac_descuentos

    #     total = (costo_art + costo_ser)-descuento

    #     return total
    
    # fac_total_pagar = property(_pagar)

    def __str__(self) -> str:
        return "%s" % (self.fac_numero_serie)

class DetalleFacturaVenta(models.Model):
    tbl_facturas_idfactura = models.ForeignKey(FacturaVenta, on_delete=models.CASCADE, verbose_name="Factura número:")
    tbl_articulos_idarticulo = models.ForeignKey(Articulos, on_delete=models.CASCADE, verbose_name="Artículos:")
    dep_precio = models.DecimalField(max_digits=8, decimal_places=2, verbose_name="Precio:")
    dep_cantidad = models.SmallIntegerField(verbose_name="Cantidad:")
    class Estado(models.TextChoices):
        ACTIVO = '1', _('Activo')
        INACTIVO = '0', _('Inactivo')
    
    def _dep_total(self):
        return self.dep_cantidad*self.dep_precio
    dep_total = property(_dep_total)

    def __str__(self) -> str:
        return "%s" % (self.tbl_articulos_idarticulo)

facturacion/forms.py
from dataclasses import field, fields
from pyexpat import model
from socket import fromshare
from django import forms
from django.forms import widgets

from facturacion.models import DetalleFacturaVenta, FacturaVenta

class FacturaVentaForm(forms.ModelForm):
    class Meta:
        model = FacturaVenta
        exclude = ['fac_estado', 'tbl_empleados_idempleado', 'fac_total_pagar', 'fac_numero_serie']
        widgets = {
            'fac_fecha': widgets.DateInput(attrs={'type':'date'}, format='%Y-%m-%d')
        }

class DetalleFacturaVentaForm(forms.ModelForm):
    class Meta:
        model = DetalleFacturaVenta
        exclude = ['tbl_facturas_idfactura',]

facturacion/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect, HttpResponse
from django.views.generic import View
import os
from django.conf import settings
from django.template import Context
from django.template.loader import get_template
from articulos.models import Articulos
from xhtml2pdf import pisa
from django.urls import reverse_lazy
from django.contrib.staticfiles import finders
from django.db.models import Q
from django.contrib.auth.decorators import login_required, permission_required

from facturacion.forms import DetalleFacturaVentaForm, FacturaVentaForm
from facturacion.models import DetalleFacturaVenta, FacturaVenta
from usuarios.models import Empleados, Empresa, Sucursales
from django.contrib import messages

# Create your views here.

@login_required(login_url='login')
@permission_required('facturacion.view_facturaventa')
def facturar_venta(request, modal_status='hid'):
    titulo = "Registrar y facturar venta"
    facturas = FacturaVenta.objects.filter(fac_estado='1')
    #detalle_factura = DetalleFacturaVenta.objects.get().all

    #print(detalle_factura)

    ### cuerpo del modal ###
    modal_title = ""
    modal_txt = ""
    modal_submit = ""
    #######################

    pk_factura = ""
    tipo = None
    form_update = None
    form = FacturaVentaForm()

    if request.method == "POST" and 'form-crear' in request.POST:
        form = FacturaVentaForm(request.POST)
        if form.is_valid():
            aux = form.save(commit=False)
            aux.tbl_empleados_idempleado = Empleados.objects.get(user_id=request.user.id)
            aux.fac_total_pagar = 0
            aux.save()
            messages.success(
                request, f"La factura {aux.fac_numero_serie} ha sido abierta"
            )
            return redirect('detalle_fac_venta', aux.fac_numero_serie)
        else:
            form = FacturaVentaForm(request.POST)
            messages.error(
                request, f"Error al abrir la factura"
            )
###################### configuracion modal de eliminacion ########################
    if  request.method == "POST" and 'form-eliminar' in request.POST:
        modal_status = 'show'
        pk_factura = request.POST['pk']
        factura = FacturaVenta.objects.get(id=pk_factura)

        ### Cuerpo del modal ###
        modal_title = f"Eliminar {factura}"
        modal_txt = f"Eliminar la factura{factura}"
        modal_submit = "Eliminar"
        ########################

        tipo = "eliminar"

#################### Configuracon modal de edicion ##############################
    if request.method == "POST" and 'form-editar' in request.POST:
        modal_status = 'show'
        pk_factura = request.POST['pk']
        factura = FacturaVenta.objects.get(id=pk_factura)

        ### Cuerpo del modal ###
        modal_title = f"Editar {factura}"
        modal_submit = "Editar"
        ########################

        tipo = "editar"
        form_update = FacturaVentaUpdateForm(instance=factura)

################### Configuración de eliminación ###############################
    if request.method == 'POST' and 'modal-confirmar' in request.POST:
        if request.POST['tipo'] == 'eliminar':
            factura = FacturaVenta.objects.filter(id = int(request.POST['modal-pk'])).update(
                fac_estado = '0'
            )
            messages.success(
                request,f"Se eliminó la factura {factura.fac_numero_serie} exitosamente!"
            )
            return redirect('facturar_venta')

        if request.POST['tipo'] == 'editar':
            pk_factura = request.POST['modal-pk']
            factura = FacturaVenta.objects.get(id=pk_factura)
            form_update = FacturaVentaUpdateForm(request.POST, instance=factura)

            if form_update.is_valid():
                form_update.save()
                messages.success(
                    request,f"Se editó la factura {factura.fac_numero_serie} exitosamente!"
                )
                return redirect('facturar_venta')
    context = {
        'titulo':titulo,
        'facturas':facturas,
        'form':form,
        'modal_status':modal_status,
        'modal_submit':modal_submit,
        'modal_title':modal_title,
        'modal_text':modal_txt,
        'pk':pk_factura,
        'tipo':tipo,
        'form_update':form_update,
        #'detalle_factura':detalle_factura,
    }
    return render(request, 'facturacion/frm_registrar_ventas.html', context)

@login_required(login_url='login')
@permission_required('facturacion.view_detallefacturaventa')
def detalle_fac_venta(request, pk):
    titulo = f"Detalle de la factura de venta {pk}"
    detalles = DetalleFacturaVenta.objects.filter(tbl_facturas_idfactura_id=pk)
    print(detalles)
    if request.method == "POST":
        form = DetalleFacturaVentaForm(request.POST)
        if form.is_valid():
            temp = form.save(commit=False)
            temp.tbl_facturas_idfactura_id = pk
            # numArt = temp.dep_cantidad
            # if numArt > Articulos.objects.filter(
            #     art_stock_disp = 
            # )
            temp.save()
            factura = FacturaVenta.objects.get(fac_numero_serie=pk)
            factura.fac_total_pagar += temp.dep_precio * temp.dep_cantidad
            factura.save()
            messages.success(
                request, f"Se agregó el artículo con codígo {request.POST['tbl_articulos_idarticulo']} existosamente"
            )
            return redirect('detalle_fac_venta', pk)
        else:
            messages.error(
                request,f"Se ha producido un error al agregar atículos"
            )
    else:
        form = DetalleFacturaVentaForm()
    context = {
        'titulo':titulo,
        'form':form,
        'detalles':detalles,
    }
    return render(request, 'facturacion/detalle_factura_venta.html', context)

@login_required(login_url='login')
@permission_required('facturacion.delete_detallefacturaventa')
def eliminar_art_detalle_fac(request, pk, tbl_facturas_idfactura):
    temp = DetalleFacturaVenta.objects.get(id=pk)

    factura = FacturaVenta.objects.get(fac_numero_serie=tbl_facturas_idfactura)
    factura.fac_total_pagar -= temp.dep_precio * temp.dep_cantidad
    factura.save()
    #DetalleFacturaVenta.objects.filter(id=pk).delete()
    temp.delete()
    messages.success(
        request,f"Se ha quitado el artículo"
    )
    return HttpResponseRedirect(request.META.get("HTTP_REFERER"))

class ImprimirFacturaVenta(View,):
    def link_callback(self, uri, rel):
            """
            Convert HTML URIs to absolute system paths so xhtml2pdf can access those
            resources
            """
            result = finders.find(uri)
            if result:
                    if not isinstance(result, (list, tuple)):
                            result = [result]
                    result = list(os.path.realpath(path) for path in result)
                    path=result[0]
            else:
                    sUrl = settings.STATIC_URL        # Typically /static/
                    sRoot = settings.STATIC_ROOT      # Typically /home/userX/project_static/
                    mUrl = settings.MEDIA_URL         # Typically /media/
                    mRoot = settings.MEDIA_ROOT       # Typically /home/userX/project_static/media/

                    if uri.startswith(mUrl):
                            path = os.path.join(mRoot, uri.replace(mUrl, ""))
                    elif uri.startswith(sUrl):
                            path = os.path.join(sRoot, uri.replace(sUrl, ""))
                    else:
                            return uri

            # make sure that file exists
            if not os.path.isfile(path):
                    raise Exception(
                            'media URI must start with %s or %s' % (sUrl, mUrl)
                    )
            return path

    def get(self, request, *args, **kwargs):
        try:
            template = get_template('facturacion/imprimir_factura.html')
            context = {
                'venta': FacturaVenta.objects.get(pk=self.kwargs['pk']),
                'icon': 'static/img/logo_racing.png',
                'detalle_venta': DetalleFacturaVenta.objects.filter(tbl_facturas_idfactura=self.kwargs['pk']),
                'empresa': Empresa.objects.get(empr_estado=1),
                'sucursal': 'Bogotá, Colombia',
            }
            html = template.render(context)
            response = HttpResponse(content_type='application/pdf')
            #response['Content-Disposition'] = 'attachment; filename="factura.pdf"'
            pisa_status = pisa.CreatePDF(
            html, dest=response,
            link_callback=self.link_callback
            )
            return response
        except:
            pass
        return HttpResponseRedirect(reverse_lazy('facturar_venta'))

@login_required(login_url='login')
@permission_required('facturacion.change_facturaventa')
def cerrar_factura(request, pk):
    FacturaVenta.objects.filter(fac_numero_serie=pk).update(
        fac_estado='2'
    )
    messages.success(
        request,f"La factura se ha cerrado exitosamente"
    )
    return redirect('facturar_venta')

def historial_ventas(request):
    titulo = "Historial ventas"
    historial_ventas_ = FacturaVenta.objects.filter(fac_estado='2')
    busqueda = request.GET.get('venta_busqueda')
    if busqueda:
        historial_ventas_ = FacturaVenta.objects.filter(
            Q(fac_numero_serie__icontains = busqueda)
        ).distinct()
    context = {
        'titulo':titulo,
        'historial_ventas_':historial_ventas_,
    }
    return render(request, 'facturacion/interfaz_historial_ventas.html', context)

def tbl_rel_factura_art_hist(request, pk):
    titulo = f"Detalle de la factura {pk}"
    rel = DetalleFacturaVenta.objects.filter(tbl_facturas_idfactura_id=pk)
    print(rel)
    context = {
        'titulo':titulo,
        'rel':rel,
    }

main/templates/facturacion/detalle_factura_venta.html
{% extends 'partials/bodyApp.html' %}
{% load crispy_forms_tags %}
{% load static %}


{% block css %}
<link rel="stylesheet" href="{% static 'css/frm_detalle_fac_venta.css' %}">
{% endblock css %}


{% block contenido %}
<div class="titulo_superior">
    <h1>Agrega artículos de la factura</h1>
</div>

<div class="form_articulos">
    <div class="sub_articulos">
        <h2>Agregar Artículo</h2>
    </div>
    
    {% if perms.facturacion.add_detallefacturaventa %}
    <form action="" method="POST" class="form1">
        {% csrf_token %}
        {{ form|crispy }}
        <button class="btn_agregar" name="agregar-producto">Agregar Artículo</button>
    </form>
    {% else %}
    <h5 class="control-group text_perms" id="div_id_tbl_articulos_idarticulo">Lo sentimos, no cuentas con los permisos editar esta orden.</h5>
    {% endif %}
</div>
<div class="contenedor_secundario">
        <div class="titulo_tabla">
            <h2>Agrega artículos a la factura</h2>
        </div>
        <div class="contenedor_tabla">
            <table>
                <thead>
                    <tr>
                        <th>Factura</th>
                        <th>Artículo</th>
                        <th>Precio</th>
                        <th>Cantidad</th>
                        <th>Total</th>
                        
                        {% if perms.facturacion.delete_detallefacturaventa %}
                        <th>Acciones</th>
                        {% endif %}
                    </tr>
                </thead>
                <tbody>
                    {% for detalle in detalles %}
                    <tr>
                        <td>{{detalle.tbl_facturas_idfactura}}</td>
                        <td>{{detalle.tbl_articulos_idarticulo}}</td>
                        <td>${{detalle.dep_precio}}</td>
                        <td>{{detalle.dep_cantidad}}</td>
                        <td>${{detalle.dep_total}}</td>
                        {% if perms.facturacion.delete_detallefacturaventa %}
                        <td>
                            <a href="#" onclick="eliminar_art_detalle_fac({{detalle.id}}, {{detalle.tbl_facturas_idfactura}})">
                                <img src="{% static 'img/eliminar.svg' %}" alt="Botón eliminar" class="btn_eliminar" title="Quitar artículo">
                            </a>
                        </td>
                        {% endif %}
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>

    {% endblock contenido %}


    {% block js %}
    <script>
        $(function () {
            $("#sidebarToggle").click();
            $("#id_tbl_articulos_idarticulo").select2({
                placeholder:"Seleccione un artículo",
                allowClear:true,
            });
        });
    </script>
    {% endblock js %}

main/templates/facturacion/frm_registrar_ventas.html
{% extends 'partials/bodyApp.html' %}
{% load crispy_forms_tags %}
{% load static %}


{% block css %}
<link rel="stylesheet" href="{% static 'css/frm_registrar_ventas.css' %}">
{% endblock css %}


{% block contenido %}
<section>
    <div class="titulo_superior">
        <h1>Registra tus ventas aquí</h1>
    </div>
    <div class="form_facturas">
        <div class="sub_frm_fac">
            <h2>Agregar Facturas</h2>
        </div>
        
        {% if perms.facturacion.add_facturaventa %}            
        <form action="" method="POST" class="form_factura">
            <h4 class="control-group" id="num_factura">El número de tu factura se generará automáticamente</h4>
            {% csrf_token %}
            {{form|crispy}}
            <input type="hidden" name="modal-status" id="modal-status" value="{{modal_status}}">
            <button class="btn_agregar" name="form-crear">Agregar factura</button>
        </form>
        {% else %}
        <h5 class="control-group text_perms" id="div_id_tbl_ordenes_servicio_idorden_servicio">Lo sentimos, no cuentas con los permisos para crear o agregar una factura.</h5>
        {% endif %}
    </div>
    <div class="contenedor_secundario">
        <div class="titulo_tabla">
            <h2>Facturas activas</h2>
        </div>
        <div class="contenedor_tabla">
            <table>
                <thead>
                    <tr>
                        <th>Órden de servicio</th>
                        <th>Empleado</th>
                        <th>Cliente</th>
                        <th>Fecha</th>
                        <th>Caja</th>
                        <th>Costo servicio</th>
                        <th>Descuentos</th>
                        <th>Total a pagar</th>
                        <th>Observaciones</th>
                        <th>Acciones</th>
                    </tr>
                </thead>
                <tbody>

                    {% for factura in facturas %}
                    <tr>
                        <td>{{factura.tbl_ordenes_servicio_idorden_servicio}}</td>
                        <td>{{factura.tbl_empleados_idempleado}}</td>
                        <td>{{factura.tbl_clientes_idcliente}}</td>
                        <td>{{factura.fac_fecha}}</td>
                        <td>{{factura.fac_caja}}</td>
                        <td>${{factura.fac_costo_servicio}}</td>
                        <td>${{factura.fac_descuentos}}</td>
                        <td>${{factura.fac_pagar_cliente}}</td>
                        <td>{{factura.fac_observaciones}}</td>
                        <td class="d-flex flex-row">
                                {% csrf_token %}
                                <a href="{% url 'detalle_fac_venta' factura.fac_numero_serie %}">
                                    <img src="{% static 'img/editar.svg' %}" alt="Botón editar" id="btn_editar" title="Editar factura">
                                </a>
                                {% if perms.facturacion.change_facturaventa %}  
                                <a href="#" onclick="cerrar_factura({{factura.fac_numero_serie}})" class="reset">
                                    <img src="{% static 'img/finalizar_tarea.svg' %}" class="btn_finalizar_tarea" alt="Cerrar factura" title="Cerrar factura">
                                </a>
                                {% endif %}

                                <a href="#" onclick="imprimir_factura_redirec({{factura.fac_numero_serie}})">
                                    <img src="{% static 'img/imprimir.svg' %}" alt="Imprimir factura" class="btn_imprimir" title="Imprimir factura">
                                </a>
                        </td>
                    </tr>
                    {% endfor %}

                </tbody>
            </table>
        </div>
    </div>
</section>
{% endblock contenido %}

{% block js %}
<script>
    $(function () {
        $("#sidebarToggle").click();
        $("#id_tbl_ordenes_servicio_idorden_servicio").select2({
            placeholder:"Selecciona una órden (opcional)",
            allowClear:true,
            width:"100%",
        });
        $("#id_tbl_clientes_idcliente").select2({
            placeholder:"Selecciona un cliente",
            allowClear:true,
            width:"100%",
        });
    });
</script>

<script src="{% static 'js/pdf_e_impresiones.js' %}"></script>
{% endblock js %}

main/templates/facturacion/interfaz_historial_dell_factura.html
{% extends 'partials/bodyApp.html' %}
{% load static %}


{% block css %}
<link rel="stylesheet" href="{% static 'css/interfaz_historial_dell_factura.css' %}">
{% endblock css %}
    

{% block contenido %}
<section>
    <div class="titulo_superior">
        <h1>Artículos de la factura</h1>
    </div>
    <!-- formulario de busqueda -->
    <h3 class="info1">Estas viendo los artículos que se vendierón en la factura que seleccionaste</h3>
    <div class="container_tabla">
        <table>
            <thead>
                <tr>
                    <th>Factura</th>
                    <th>Artículos</th>
                    <th>Cantidad</th>
                    <th>Precio</th>
                    <th>Total</th>

                </tr>
            </thead>
            <tbody>
                {% for rel in rel %}
                <tr>
                    <td>{{rel.tbl_facturas_idfactura}}</td>
                    <td>{{rel.tbl_articulos_idarticulo}}</td>
                    <td>{{rel.dep_cantidad}}</td>
                    <td>${{rel.dep_precio}}</td>
                    <td>${{rel.dep_total}}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</section>
{% endblock contenido %}

main/templates/facturacion/interfaz_historial_ventas.html
{% extends 'partials/bodyApp.html' %}
{% load static %}


{% block css %}
<link rel="stylesheet" href="{% static 'css/interfaz_historial_ventas.css' %}">
{% endblock css %}
    

{% block contenido %}
<section>
    <div class="titulo_superior">
        <h1>Historial de ventas</h1>
    </div>
    <!-- formulario de busqueda -->
    <form method="GET">
        <label for="idOrdSBusqueda" class="label_buscar">Buscar venta:</label>
        <input type="search" name="venta_busqueda" id="idOrdSBusqueda" value="{{request.GET.venta_busqueda}}" placeholder="Buscar">

        <button type="submit" id="btn_mostrar_filtro" class="btn btn-outline-success"><i class="bi bi-search"></i></button>
    </form>
    <div class="container_tabla">
        <table>
            <thead>
                <tr>
                    <th>Órden de servicio</th>
                    <th>Empleado</th>
                    <th>Cliente</th>
                    <th>Fecha</th>
                    <th>Caja</th>
                    <th>Descuentos</th>
                    <th>Total a pagar</th>
                    <th>Observaciones</th>
                    
                    {% if perms.facturacion.view_facturaventa or perms.facturacion.delete_facturaventa %}           
                    <th>Acciones</th>
                    {% endif %}
                </tr>
            </thead>
            <tbody>

                {% for factura in historial_ventas_ %}
                <tr>
                    <td>{{factura.tbl_ordenes_servicio_idorden_servicio}}</td>
                    <td>{{factura.tbl_empleados_idempleado}}</td>
                    <td>{{factura.tbl_clientes_idcliente}}</td>
                    <td>{{factura.fac_fecha}}</td>
                    <td>{{factura.fac_caja}}</td>
                    <td>${{factura.fac_descuentos}}</td>
                    <td>${{factura.fac_total_pagar}}</td>
                    <td>{{factura.fac_observaciones}}</td>
                    {% if perms.facturacion.view_facturaventa or perms.facturacion.delete_facturaventa %}           
                    <td class="d-flex flex-row">
                        {% csrf_token %}
                        {% if perms.facturacion.view_facturaventa %}
                        <a href="{% url 'historial_detalle_factura' factura.fac_numero_serie %}">
                            <img src="{% static 'img/ver.svg' %}" alt="Botón ver detalles" title="Ver detalles">
                        </a>
                        {% endif %}
                        
                        {% if perms.facturacion.delete_facturaventa %}
                        <a href="#" onclick="eliminar_registros({{factura.fac_numero_serie}})">
                            <img src="{% static 'img/eliminar.svg' %}" alt="Botón eliminar" id="btn_eliminar" title="Eliminar del historial">
                        </a>
                        {% endif %}
                        
                        {% if perms.facturacion.view_facturaventa %}
                        <a href="#" onclick="imprimir_factura_redirec({{factura.fac_numero_serie}})">
                            <img src="{% static 'img/imprimir.svg' %}" alt="Imprimir factura" class="btn_imprimir" title="Imprimir factura">
                        </a>
                        {% endif %}
                    </td>
                    {% endif %}

                </tr>
                {% endfor %}

            </tbody>
        </table>
    </div>
    <a href="{% url 'facturar_venta' %}" id="ancla">
        <img src="{% static 'img/anadir.svg' %}" alt="Boton añadir" id="btn_anadir" title="Crear nueva órden">
    </a>
</section>
{% endblock contenido %}


{% block js %}
<script src="{% static 'js/pdf_e_impresiones.js' %}"></script>
{% endblock js %}
    