articulos/urls.py
from tokenize import Name
from django.urls import path

from articulos.views import articulos, categorias, editar_articulo, editar_categoria, editar_marca, editar_proveedor, eliminar_articulo, eliminar_categoria, eliminar_marca, eliminar_proveedor, marcas, proveedores, registrar_articulo, registrar_proveedor

urlpatterns = [
    path('articulos/', articulos, name="articulos"),
    path('articulos/crear/', registrar_articulo, name="registrar_articulo"),
    path('articulos/editar/<int:pk>/', editar_articulo, name="editar_articulo"),
    path('articulos/eliminar/<int:pk>/', eliminar_articulo, name="eliminar_articulo"),
    path('articulos/categorias/', categorias, name="categorias"),
    path('articulos/categorias/editar/<int:pk>/', editar_categoria, name="editar_categoria"),
    path('articulos/categorias/eliminar/<int:pk>/', eliminar_categoria, name="eliminar_categoria"),
    path('vehiculos/marcas/', marcas, name="marcas"),
    path('vehiculos/marcas/editar/<int:pk>/', editar_marca, name="editar_marca"),
    path('vehiculos/marcas/eliminar/<int:pk>/', eliminar_marca, name="eliminar_marca"),
    path('proveedores/', proveedores, name="proveedores"),
    path('proveedores/crear/', registrar_proveedor, name="registrar_proveedor"),
    path('proveedores/editar/<int:pk>/', editar_proveedor, name="editar_proveedor"),
    path('proveedores/eliminar/<int:pk>/', eliminar_proveedor, name="eliminar_proveedor"),

]

main/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import handler404, handler500
from django.contrib.auth import views as auth_views

###### Importes para subir imagenes #####
from django.conf import settings
from django.conf.urls.static import static
#########################################

from main.views import inicio, inicioAdmin, logout_user, nosotros, soporte_ayuda, Error404, Error500

# handler404= Error_404.as_view()s

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', inicio, name='inicio'),
    # path('loggein/', loggedIn, name='inicio-sesion'),
    path('logout/',logout_user,name='logout'),
    path('adm/', inicioAdmin, name='inicio-admin'),
    #path('login/', login.as_view(), name="login"),
    path('login/', auth_views.LoginView.as_view(), name="login"),
    path('reset_password/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('reset_password_send/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset_password_complete', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    path('nosotros/', nosotros, name='nosotros'),
    path('', include('articulos.urls')),
    path('', include('usuarios.urls')),
    path('', include('inventario.urls')),
    path('', include('facturacion.urls')),
    path('', include('django.contrib.auth.urls')),
    #path("select2/", include('django_select2.urls')),
    path('soporte-ayuda/', soporte_ayuda, name="soporte_ayuda"),
]

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

handler404= Error404.as_view()

handler500 = Error500.as_error_view()

articulos/models.py
from email.policy import default
from tabnanny import verbose
from django.db import models
from django.utils.translation import gettext_lazy as _

# Create your models here.
class Proveedores(models.Model):
    pro_nit = models.CharField(max_length=20, verbose_name="Nit/Referencia:")
    pro_nombre = models.CharField(max_length=50, verbose_name="Nombre:")
    pro_categoria = models.CharField(max_length=50, verbose_name="Categoría:") #Pregunta seleccion multiple
    pro_persona_nat = models.CharField(max_length=50, verbose_name="Persona natural:")
    pro_direccion = models.CharField(max_length=100, verbose_name="Dirección:")
    pro_telefono = models.CharField(max_length=20, verbose_name="Teléfono:")
    pro_celular = models.CharField(max_length=20, verbose_name="Celular:")
    pro_email = models.EmailField(max_length=100, verbose_name="Email:")
    pro_sitio_web = models.CharField(max_length=300, verbose_name="Sitio web:")

    class Estado(models.TextChoices):
        ACTIVO = '1', _('Activo')
        INACTIVO = '0', _('Inactivo')
    pro_estado = models.CharField(max_length=1, choices=Estado.choices, default=Estado.ACTIVO, verbose_name="Estado")

    def __str__(self) -> str:
        return "%s" % (self.pro_nombre)

class Categoria(models.Model):
    cat_nombre = models.CharField(max_length=50, verbose_name="Nombre:")
    cat_descripcion = models.TextField(max_length=100, verbose_name="Descripción:")

    class Estado(models.TextChoices):
        ACTIVO = '1', _('Activo')
        INACTIVO = '0', _('Inactivo')
    cat_estado = models.CharField(max_length=1, choices=Estado.choices, default=Estado.ACTIVO, verbose_name="Estado")        

    def __str__(self) -> str:
        return "%s" % (self.cat_nombre)

class Marcas(models.Model):
    mar_nombre = models.CharField(max_length=50, verbose_name="Nombre:")
    mar_descripcion = models.TextField(max_length=200, verbose_name="Descripción:")

    class Estado(models.TextChoices):
        ACTIVO = '1', _('Activo')
        INACTIVO = '0', _('Inactivo')
    mar_estado = models.CharField(max_length=1, choices=Estado.choices, default=Estado.ACTIVO, verbose_name="Estado")

    def __str__(self) -> str:
        return "%s" % (self.mar_nombre)

class Articulos(models.Model):
    art_nombre = models.CharField(max_length=50, verbose_name="Nombre:")
    tbl_categoria_idcategoria = models.ForeignKey(Categoria, on_delete=models.CASCADE, verbose_name="Categoría:")
    art_precio = models.DecimalField(max_digits=10, decimal_places=2, verbose_name="Precio:")
    art_descripcion = models.TextField(max_length=500, verbose_name="Descripción:")
    art_stock_minimo = models.SmallIntegerField(verbose_name="Stock mínimo:")
    art_stock_maximo = models.SmallIntegerField(verbose_name="Stock máximo:")
    tbl_proveedores_idproveedor = models.ForeignKey(Proveedores, on_delete=models.CASCADE, verbose_name="Proveedor:")
    tbl_marcas_idmarca = models.ForeignKey(Marcas, on_delete=models.CASCADE, verbose_name="Marca:")
    art_foto = models.ImageField(upload_to='images/articulos/', blank=True, default='images/articulos/default.png', verbose_name="Foto:")

    class Estado(models.TextChoices):
        ACTIVO = '1', _('Activo')
        INACTIVO = '0', _('Inactivo')
    art_estado = models.CharField(max_length=1, choices=Estado.choices, default=Estado.ACTIVO, verbose_name="Estado")

    def _stock(self):
        from django.db.models import Sum
        from inventario.models import TblRelPedidosArticulos
        from facturacion.models import DetalleFacturaVenta

        compras = TblRelPedidosArticulos.objects.filter(
            tbl_articulos_idarticulo = self
        ).aggregate(Sum('rel_articulo_cantidad'))

        ventas = DetalleFacturaVenta.objects.filter(
            tbl_articulos_idarticulo = self
        ).aggregate(Sum('dep_cantidad'))

        total = ((compras.get('rel_articulo_cantidad__sum') if compras.get('rel_articulo_cantidad__sum') is not None else 0)-(ventas.get('dep_cantidad__sum') if ventas.get('dep_cantidad__sum') is not None else 0))

        return total

    art_stock_disp = property(_stock)

    def __str__(self) -> str:
        return "%s | %s" % (self.art_nombre, self.art_stock_disp)

articulos/views.py
from django.shortcuts import render, redirect
from multiprocessing import context
from articulos.forms import ArticulosForm, CategoriasForm, MarcasForm, ProveedoresForm
from django.contrib import messages
from django.db.models import Q
from django.contrib.auth.decorators import login_required, permission_required

from articulos.models import Articulos, Categoria, Marcas, Proveedores


# Create your views here

@login_required(login_url='login')
@permission_required('articulos.view_articulos')
def articulos(request):
    titulo = "Artículos"
    articulos = Articulos.objects.filter(art_estado = '1')
    busqueda = request.GET.get('art_busqueda')
    if busqueda:
        articulos = Articulos.objects.filter(
            Q(id__icontains = busqueda) |
            Q(art_nombre__icontains = busqueda)
        ).distinct()
    context = {
        'titulo':titulo,
        'articulos':articulos,
    }
    return render(request, 'articulos/interfaz_articulos.html', context)

@login_required(login_url='login')
@permission_required('articulos.add_articulos')
def registrar_articulo(request):
    titulo = "Registrar nuevo artículo"
    if request.method == "POST":
        form = ArticulosForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            messages.success(
                request,f"Se agregó el articulo {request.POST['art_nombre']} exitosamente"
            )
            return redirect('articulos')
        else:
            messages.error(
                request,f"Se ha producido un error al guardar el artículo"
            )
    else:
        form = ArticulosForm()

    context = {
        'titulo': titulo,
        'form': form
    }
    return render(request, 'articulos/frm_registrar_articulos.html', context)

@login_required(login_url='login')
@permission_required('articulos.change_articulos')
def editar_articulo(request, pk):
    titulo = "Editar artículo"
    articulo = Articulos.objects.get(id=pk)
    if request.method == "POST":
        form = ArticulosForm(request.POST, request.FILES, instance=articulo)
        if form.is_valid():
            form.save()
            messages.success(
                request,f"Se editó el artículo {request.POST['art_nombre']} exitosamente"
            )
            return redirect('articulos')
        else:
            messages.error(
                request,f"Se ha producido un error al editar el artículo"
            )
    else:
        form = ArticulosForm(instance=articulo)

    context = {
        'titulo': titulo,
        'form': form
    }
    return render(request, 'articulos/frm_registrar_articulos.html', context)

@login_required(login_url='login')
@permission_required('articulos.delete_articulos')
def eliminar_articulo(request, pk):
    Articulos.objects.filter(id=pk).update(
        art_estado='0'
    )
    messages.success(
        request,f"El artículo se eliminó exitosamente"
    )
    return redirect('articulos')

@login_required(login_url='login')
@permission_required('articulos.view_categoria')
def categorias(request):
    titulo = "Categorías en artículos"
    categorias = Categoria.objects.filter(cat_estado = '1')
    busqueda = request.GET.get('cat_busqueda')
    if busqueda:
        categorias = Categoria.objects.filter(
            Q(id__icontains = busqueda) |
            Q(cat_nombre__icontains = busqueda)
        ).distinct()
    if request.method == "POST":
        form = CategoriasForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(
                request,f"Se agregó la categoría {request.POST['cat_nombre']} exitosamente"
            )
            return redirect('categorias')
        else:
            messages.error(
                request,f"Se ha producido un error al guardar la categoría"
            )
    else:
        form = CategoriasForm()
    context = {
        'titulo': titulo,
        'categorias': categorias,
        'form': form
    }
    return render(request, 'articulos/interfaz_categorias.html', context)

@login_required(login_url='login')
@permission_required('articulos.change_categoria')
def editar_categoria(request, pk):
    titulo = "Editar categoría"
    categoria = Categoria.objects.get(id=pk)
    if request.method == "POST":
        form = CategoriasForm(request.POST, instance=categoria)
        if form.is_valid():
            form.save()
            messages.success(
                request,f"Se editó la categoría {request.POST['cat_nombre']} exitosamente"
            )
            return redirect('categorias')
        else:
            messages.error(
                request,f"Se ha producido un error al editar la categoría"
            )
    else:
        form = CategoriasForm(instance=categoria)

    context = {
        'titulo': titulo,
        'form': form
    }
    return render(request, 'articulos/interfaz_categorias.html', context)

@login_required(login_url='login')
@permission_required('articulos.delete_categoria')
def eliminar_categoria(request, pk):
    Categoria.objects.filter(id=pk).update(
        cat_estado='0'
    )
    messages.success(
        request,f"La categoría se eliminó exitosamente"
    )    
    return redirect('categorias')

@login_required(login_url='login')
@permission_required('articulos.view_marcas')
def marcas(request):
    titulo = "Marcas"
    marcas = Marcas.objects.filter(mar_estado = '1')
    busqueda = request.GET.get('mar_busqueda')
    if busqueda:
        marcas = Marcas.objects.filter(
            Q(id__icontains = busqueda) |
            Q(mar_nombre__icontains = busqueda)
        ).distinct()
    if request.method == "POST":
        form = MarcasForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(
                request,f"Se agregó la marca {request.POST['mar_nombre']} exitosamente"
            )
            return redirect('marcas')
        else:
            messages.error(
                request,f"Se ha producido un error al guardar la marca"
            )
    else:
        form = MarcasForm()
    context = {
        'titulo': titulo,
        'marcas': marcas,
        'form': form
    }
    return render(request, 'articulos/interfaz_marcas.html', context)


@login_required(login_url='login')
@permission_required('articulos.change_marcas')
def editar_marca(request, pk):
    titulo = "Editar marca"
    marca = Marcas.objects.get(id=pk)
    if request.method == "POST":
        form = MarcasForm(request.POST, instance=marca)
        if form.is_valid():
            form.save()
            messages.success(
                request,f"Se editó la marca {request.POST['mar_nombre']} exitosamente"
            )
            return redirect('marcas')
        else:
            messages.error(
                request,f"Se ha producido un error al editar la marca"
            )
    else:
        form = MarcasForm(instance=marca)

    context = {
        'titulo': titulo,
        'form': form
    }
    return render(request, 'articulos/interfaz_marcas.html', context)

@login_required(login_url='login')
@permission_required('articulos.delete_marcas')
def eliminar_marca(request, pk):
    Marcas.objects.filter(id=pk).update(
        mar_estado='0'
    )
    messages.success(
        request,f"La marca se eliminó exitosamente"
    )
    return redirect('marcas')

@login_required(login_url='login')
@permission_required('articulos.view_proveedores')
def proveedores(request):
    titulo = "Proveedores"
    proveedores = Proveedores.objects.filter(pro_estado = '1')  # ver formulario
    busqueda = request.GET.get('pro_busqueda')
    if busqueda:
        proveedores = Proveedores.objects.filter(
            Q(id__icontains = busqueda) |
            Q(pro_nit__icontains = busqueda) |
            Q(pro_nombre__icontains = busqueda)
        ).distinct()
    context = {
        'titulo': titulo,
        'proveedores': proveedores
    }
    return render(request, 'articulos/interfaz_proveedores.html', context)

@login_required(login_url='login')
@permission_required('articulos.add_proveedores')
def registrar_proveedor(request):
    titulo = "Registrar nuevo proveedor"
    if request.method == "POST":
        form = ProveedoresForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(
                request,f"Se agregó el proveedor {request.POST['pro_nombre']} exitosamente"
            )
            return redirect('proveedores')
        else:
            messages.error(
                request,f"Se ha producido un error al guardar el proveedor"
            )
    else:
        form = ProveedoresForm()

    context = {
        'titulo': titulo,
        'form': form
    }
    return render(request, 'articulos/frm_registrar_proveedores.html', context)

@login_required(login_url='login')
@permission_required('articulos.change_proveedores')
def editar_proveedor(request, pk):
    titulo = "Editar proveedor"
    proveedor = Proveedores.objects.get(id=pk)
    if request.method == "POST":
        form = ProveedoresForm(request.POST, instance=proveedor)
        if form.is_valid():
            form.save()
            messages.success(
                request,f"Se editó el proveedor {request.POST['pro_nombre']} exitosamente"
            )
            return redirect('proveedores')
        else:
            messages.error(
                request,f"Se ha producido un error al editar el proveedor"
            )
    else:
        form = ProveedoresForm(instance=proveedor)

    context = {
        'titulo': titulo,
        'form': form
    }
    return render(request, 'articulos/frm_registrar_proveedores.html', context)

@login_required(login_url='login')
@permission_required('articulos.delete_proveedores')
def eliminar_proveedor(request, pk):
    Proveedores.objects.filter(id=pk).update(
        pro_estado='0'
    )
    messages.success(
        request,f"El proveedor se eliminó exitosamente"
    )
    return redirect('proveedores')

main/templates/articulos/frm_registrar_articulos.html
{% extends 'partials/bodyApp.html' %}
{% load crispy_forms_tags %}
{% load static %}


{% block css %}
    <link rel="stylesheet" href="{% static 'css/frm_registrar_articulos.css' %}">
{% endblock css %}
    

{% block contenido %}
    <div id="titulo_superior">
        <h1>Registrar nuevo artículo</h1>
    </div>
    <form action="" method="POST" enctype="multipart/form-data">
            {{form|crispy}}
            {% csrf_token %}
        <div class="frame_b f8">
            <button type="submit" id="btn_guardar">Guardar</button>
            <button type="reset" id="btn_cancelar">Cancelar</button>
        </div>
    </form>
    <img src="{% static 'img/registrar_articulo.svg' %}" alt="Icono alucivo a artículos" id="img1">
    <a href="frm_registrar_proveedores.html" id="texto_guia1" title="Click para registrar un nuevo proveedor">
        <b>Nota: </b> <br> si el proveedor del artículo que va agregar aún no esta en la base de datos, por favor, registre aquí el proveedor antes de registrar el artículo.
    </a>
    <div class="espacio"></div>
{% endblock contenido %}


{% block js %}
<script>
    $(function () {
        $("#sidebarToggle").click();
        $("#id_tbl_categoria_idcategoria").select2({
            placeholder:"Selecciona una categoría",
            allowClear:true,
            width:"100%",
        });
        $("#id_tbl_proveedores_idproveedor").select2({
            placeholder:"Selecciona un proveedor",
            allowClear:true,
            width:"100%",
        });
        $("#id_tbl_marcas_idmarca").select2({
            placeholder:"Selecciona una marca",
            allowClear:true,
            width:"100%",
        });
    });
</script>
{% endblock js %}
    

main/templates/articulos/frm_registrar_proveedores.html
{% extends 'partials/bodyApp.html' %}
{% load crispy_forms_tags %}
{% load static %}


{% block css %}
<link rel="stylesheet" href="{% static 'css/frm_registrar_proveedor.css' %}">
{% endblock css %}


{% block contenido %}
<div class="titulo">
  <h1>Registrar nuevo proveedor</h1>
</div>
<form action="" method="POST">
  {{form|crispy}}
  {% csrf_token %}
  <div class="frame_b">
    <button id="btn_guardar" type="submit ">Guardar</button>
    <button id="btn_cancelar" type="reset">Cancelar</button>
  </div>
  <img src="{% static 'img/registrar_proveedores.svg' %}" alt="Icono alucivo a proveedores" id="icono_add_proveedor"> 
</form>
{% endblock contenido %}


{% block js %}
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
  integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
{% endblock js %}
  

main/templates/articulos/interfaz_categorias.html
{% extends 'partials/bodyApp.html' %}
{% load crispy_forms_tags %}
{% load static %}


{% block css %}
<link rel="stylesheet" href="{% static 'css/interfaz_categorias.css' %}">
{% endblock css %}
    

{% block contenido %}
<section>
    <div class="titulo_superior">
        <h2>Categorías en artículos establecidas</h2>
    </div>
    <div class="contenedor_form">
        <form method="GET">
            <label for="CatBusqueda" class="label_buscar">Buscar categoría:</label>
            <input type="search" name="cat_busqueda" id="CatBusqueda" value="{{request.GET.cat_busqueda}}" placeholder="Buscar">
    
            <button type="submit" id="btn_mostrar_filtro" class="btn btn-outline-success"><i class="bi bi-search"></i></button>
        </form>
    </div>
    <div class="contenedor_tabla">
        <table>
            <thead>
                <tr>
                    <th>ID</th>
                    <th>Nombre</th>
                    <th>Descripción</th>
                    
                    {% if perms.articulos.change_categoria or perms.articulos.delete_categoria %}           
                    <th>Acciones</th>
                    {% endif %}
                </tr>
                </tr>
            </thead>
            <tbody>

                {% for categoria in categorias %}
                <tr>
                    
                        <td>{{categoria.pk}}</td>
                        <td>{{categoria.cat_nombre}}</td>
                        <td>{{categoria.cat_descripcion}}</td>
                        {% if perms.articulos.change_categoria or perms.articulos.delete_categoria %}           
                        <td>
                            
                            {% if perms.articulos.change_categoria %}                                
                            <a href="{% url 'editar_categoria' categoria.id %}">
                                <img src="{% static 'img/editar.svg' %}" alt="Botón editar" id="btn_editar" title="Editar categoría">
                            </a>
                            {% endif %}
                            
                            {% if perms.articulos.delete_categoria %}                                
                            <a href="#" onclick="eliminar_registros({{ categoria.id }})">
                                <img src="{% static 'img/eliminar.svg' %}" alt="Botón editar" id="btn_eliminar" title="Mover a papelera">
                            </a>
                            {% endif %}
                        </td>
                        {% endif %}
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
    <img src="{% static 'img/categoriasArt.svg' %}" alt="Ilustración relativa a categorías" id="img1">
    
    {% if perms.articulos.add_categoria %}
    <a href="#" id="btn_anadir" title="Añadir nueva categoría">Añadir</a>
    {% endif %}
</section>
<section class="modal-form-cat ">
    <div class="container_modal-form-cat">
        <div class="container_h2-form-cat">
            <h2>Añadir nueva categoría</h2>
            <a href="#" class="modal_close-form-cat container_cerrar-form-cat">
                <img src="{% static 'img/cerrar.svg' %}" alt="Icono cerrar ventana" title="Cerrar">
            </a>
        </div>
        <img src="{% static 'img/categoriasArt.svg' %}" alt="Imagen ilustrativa a categorías" id="img2">
        
        {% if perms.articulos.add_categoria %}         
        <form action="" method="POST">
            {{form|crispy}}
            {% csrf_token %}
            <div class="frame_b">
                <button type="submit" value="Guardar" id="btn_guardar">Guardar</button>
                <button type="reset" value="Cacelar" id="btn_cancelar">Cancelar</button>
            </div>
        </form>
        {% endif %}
    </div>
</section>
{% endblock contenido %}


{% block js %}
    <script src="{% static 'js/interfaz_categorias.js' %}"></script>
{% endblock js %}
    

main/templates/articulos/interfaz_marcas.html
{% extends 'partials/bodyApp.html' %}
{% load crispy_forms_tags %}
{% load static %}


{% block css %}
<link rel="stylesheet" href="{% static 'css/interfaz_marcas.css' %}">
{% endblock css %}


{% block contenido %}
<section>
    <div class="titulo_superior">
        <h2>Marcas establecidas</h2>
    </div>
    <div class="contenedor_form">
        <form method="GET">
            <label for="MarABusqueda" class="label_buscar">Buscar marca:</label>
            <input type="search" name="mar_busqueda" id="MarABusqueda" value="{{request.GET.mar_busqueda}}" placeholder="Buscar">
    
            <button type="submit" id="btn_mostrar_filtro" class="btn btn-outline-success"><i class="bi bi-search"></i></button>
        </form>
    </div>
    <div class="contenedor_tabla">
        <table>
            <thead>
                <tr>
                    <th>ID</th>
                    <th>Nombre</th>
                    <th>Descripción</th>
                    
                    {% if perms.articulos.change_marcas or perms.articulos.delete_marcas %}           
                    <th>Acciones</th>
                    {% endif %}
                </tr>
                </tr>
            </thead>
            <tbody>

                {% for marca in marcas %}
                <tr>
                    
                        <td>{{marca.pk}}</td>
                        <td>{{marca.mar_nombre}}</td>
                        <td>{{marca.mar_descripcion}}</td>
                        
                        {% if perms.articulos.change_marcas or perms.articulos.delete_marcas %}                            
                        <td>
                            
                            {% if perms.articulos.change_marcas %}
                            <a href="{% url 'editar_marca' marca.id %}">
                                <img src="{% static 'img/editar.svg' %}" alt="Botón editar" id="btn_editar" title="Editar marca">
                            </a>
                            {% endif %}
                            
                            {% if perms.articulos.delete_marcas %}                          
                            <a href="#" onclick="eliminar_registros({{ marca.id }})">
                                <img src="{% static 'img/eliminar.svg' %}" alt="Botón editar" id="btn_eliminar" title="Mover a papelera">
                            </a>
                            {% endif %}
                        </td>
                        {% endif %}
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
    <img src="{% static 'img/Data_Arranging_Outline1.svg' %}" alt="Ilustración relativa a marcas" id="img1">
    {% if perms.articulos.add_marcas %}
    <a href="#" id="btn_anadir" title="Añadir nueva marca">Añadir</a>
    {% endif %}
</section>
<section class="modal-form1 ">
    <div class="container_modal-form1">
        <div class="container_h2-form1">
            <h2>Registrar nueva marca</h2>
            <a href="#" class="modal_close-form1 container_cerrar-form1">
                <img src="{% static 'img/cerrar.svg' %}" alt="Icono cerrar ventana" title="Cerrar">
            </a>
        </div>
        <img src="{% static 'img/Data Arranging_Flatline.svg' %}" alt="Imagen ilustrativa a marcas" id="img2">
        
        {% if perms.articulos.add_marcas %}            
        <form action="" method="POST">
            {{form|crispy}}
            {% csrf_token %}
            <div class="frame_b">
                <button type="submit" value="Guardar" id="btn_guardar">Guardar</button>
                <button type="reset" value="Cacelar" id="btn_cancelar">Cancelar</button>
            </div>
        </form>
        {% endif %}
    </div>
</section>
{% endblock contenido %}
    

{% block js %}
<script src="{% static 'js/modal_form1.js' %}"></script>
{% endblock js %}
    