inventario/urls.py
from django.urls import path

from inventario.views import ImprimirOrdenCompra, cerrar_orden_compra, cerrar_pedido, eliminar_compra_pedido, eliminar_orden_compra, historial_compras, historial_delt_ord_compra, historial_delt_pedido, historial_ord_compra, ordenes_compra, quitar_art_det_ord_compra, quitar_art_rel_pedido, registrar_pedidos_compras, reporte_semanal, tbl_rel_orden_com_articulos, tbl_rel_pedido_articulos

urlpatterns = [
    path('compras/crear-orden-de-compra/', ordenes_compra, name='ordenes_compra'),
    path('compras/crear-orden-de-compra/articulos/<int:pk>/', tbl_rel_orden_com_articulos, name='detalle_orden_compra'),
    path('compras/crear-orden-de-compra/articulos/eliminar/<int:pk>/', quitar_art_det_ord_compra, name='quitar_art_det_ord_compra'),
    path('compras/crear-orden-de-compra/imprimir/<int:pk>/', ImprimirOrdenCompra.as_view(), name='imprimir_orden_compra'),
    path('compras/crear-orden-de-compra/cerrar/<int:pk>/', cerrar_orden_compra, name='cerrar_orden_compra'),
    path('compras/registrar-compra-pedido/', registrar_pedidos_compras, name='registrar_pedido_compra'),
    path('compras/registrar-compra-pedido/cerrar/<int:pk>/', cerrar_pedido, name='cerrar_pedido'),
    path('compras/historial/eliminar/<int:pk>/', eliminar_compra_pedido, name='eliminar_compra_pedido'),
    path('compras/registrar-compra-pedido/articulos/<int:pk>/', tbl_rel_pedido_articulos, name='detalle_compra_pedidos'),
    path('compras/registrar-compra-pedido/articulos/quitar/<int:pk>/', quitar_art_rel_pedido, name='quitar_art_rel_pedido'),
    path('compras/historial/', historial_compras, name='historial_compras'),
    path('compras/historial/articulos/<int:pk>/', historial_delt_pedido, name='historial_delt_pedido'),
    path('compras/historial-ordenes-de-compra/', historial_ord_compra, name='historial_ord_compra'),
    path('compras/historial-ordenes-de-compra/articulos/<int:pk>/', historial_delt_ord_compra, name='historial_delt_ord_compra'),
    path('compras/historial-ordenes-de-compra/eliminar/<int:pk>/', eliminar_orden_compra, name='eliminar_orden_compra'),
    path('reportes/semanal/', reporte_semanal, name='reporte_semanal')
]

main/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import handler404, handler500
from django.contrib.auth import views as auth_views

###### Importes para subir imagenes #####
from django.conf import settings
from django.conf.urls.static import static
#########################################

from main.views import inicio, inicioAdmin, logout_user, nosotros, soporte_ayuda, Error404, Error500

# handler404= Error_404.as_view()s

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', inicio, name='inicio'),
    # path('loggein/', loggedIn, name='inicio-sesion'),
    path('logout/',logout_user,name='logout'),
    path('adm/', inicioAdmin, name='inicio-admin'),
    #path('login/', login.as_view(), name="login"),
    path('login/', auth_views.LoginView.as_view(), name="login"),
    path('reset_password/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('reset_password_send/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset_password_complete', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    path('nosotros/', nosotros, name='nosotros'),
    path('', include('articulos.urls')),
    path('', include('usuarios.urls')),
    path('', include('inventario.urls')),
    path('', include('facturacion.urls')),
    path('', include('django.contrib.auth.urls')),
    #path("select2/", include('django_select2.urls')),
    path('soporte-ayuda/', soporte_ayuda, name="soporte_ayuda"),
]

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

handler404= Error404.as_view()

handler500 = Error500.as_error_view()

inventario/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _
from articulos.models import Articulos, Proveedores

from usuarios.models import Empleados

# Create your models here.

class OrdenCompra(models.Model):
    ord_empleado = models.ForeignKey(Empleados, on_delete=models.CASCADE, verbose_name="Empleado responsable:")
    ord_lugar_emision = models.CharField(max_length=50, verbose_name="Lugar de emisión:")
    ord_direccion = models.CharField(max_length=80, verbose_name="Dirección:")
    ord_telefono = models.CharField(max_length=20, blank=True, verbose_name="Teléfono:")
    ord_celular = models.CharField(max_length=20, verbose_name="Celular:")
    ord_email = models.EmailField(max_length=100, verbose_name="Email:")
    ord_fecha = models.DateField(verbose_name="Fecha:")
    ord_proveedor = models.ForeignKey(Proveedores, on_delete=models.CASCADE, verbose_name="Proveedor:")
    class TerminoPago(models.TextChoices):
        METODO1 = 'Pago de contado con efectivo', _('Pago de contado con efectivo')
        METODO2 = 'Pago de contado con tarjeta', _('Pago de contado con tarjeta')
        METODO3 = 'A crédito', _('A crédito')
        METODO4 = 'Pago anticipado con efectivo', _('Pago anticipado con efectivo')
        METODO5 = 'Pago anticipado con tarjeta', _('Pago anticipado con tarjeta')
        METODO6 = 'Otro', _('Otro')
    ord_termino_pago = models.CharField(max_length=28, choices=TerminoPago.choices, verbose_name="Término de pago:")
    class TerminoEntrega(models.TextChoices):
        DOMICILIO = 'Domicilio', _('Domicilio')
        PERSONAL = 'Entrega persononal', _('Entrega personal')
        OTRO = 'Otro', _('Otro')
    ord_termino_entrega = models.CharField(max_length=18, choices=TerminoEntrega.choices, verbose_name="Término de entrega para el pedido")
    ord_otras_tarifas = models.DecimalField(max_digits=7, decimal_places=2, default=0, verbose_name="Ótras tarifas:", blank=True)
    #ord_costo_total = models.DecimalField(max_digits=10, decimal_places=2, default=0, verbose_name="Costo total estimado:")
    class Estado(models.TextChoices):
        ACTIVO = '1', _('Activo')
        INACTIVO = '0', _('Inactivo')
        CAERRADA = '2', _('Cerrada')
    ord_estado = models.CharField(max_length=1, choices=Estado.choices, default=Estado.ACTIVO,  verbose_name="Estado:")

    def _ord_costo_estimado(self):
        from django.db.models import Sum
        from inventario.models import TblRelOrdenCompraArticulos

        articulos = TblRelOrdenCompraArticulos.objects.filter(
            tbl_orden_compras_idorden_compra = self
        ).aggregate(Sum('rel_precio'))
        
        costo_total = articulos.get('rel_precio__sum') if articulos.get('rel_precio__sum') is not None else 0

        return costo_total
    
    ord_costo_estimado = property(_ord_costo_estimado)

    def __str__(self) -> str:
        return "%s" % (self.id)

class TblRelOrdenCompraArticulos(models.Model):
    tbl_orden_compras_idorden_compra = models.ForeignKey(OrdenCompra, on_delete=models.CASCADE, verbose_name="Órden de compra:")
    tbl_articulos_idarticulo = models.ForeignKey(Articulos, on_delete=models.CASCADE, verbose_name="Artículo:")
    rel_cantidad = models.SmallIntegerField(verbose_name="Cantidad:")
    rel_precio = models.DecimalField(max_digits=8, decimal_places=2, verbose_name="Precio unitario:")
    def _rel_total(self):
        return self.rel_cantidad*self.rel_precio
    rel_total = property(_rel_total)

class Pedidos(models.Model):
    ped_recivido_por = models.CharField(max_length=80, verbose_name="Recibido por:")
    ped_fecha_recivido = models.DateField(verbose_name="Fecha de recibido:")
    ped_precio = models.DecimalField(max_digits=10, decimal_places=2, verbose_name="Precio total:")
    class Estado(models.TextChoices):
        ACTIVO = '1', _('Activo')
        INACTIVO = '0', _('Inactivo')
        CERRADO = '2', _('Cerrado')
    ped_estado = models.CharField(max_length=1, choices=Estado.choices, default=Estado.ACTIVO,  verbose_name="Estado:")
    def __str__(self) -> str:
        return "%s" % (self.id)

class TblRelPedidosArticulos(models.Model):
    tbl_pedidos_idpedido = models.ForeignKey(Pedidos, on_delete=models.CASCADE, verbose_name="Pedido número:")
    tbl_articulos_idarticulo = models.ForeignKey(Articulos, on_delete=models.CASCADE, verbose_name="Artículo:")
    rel_articulo_cantidad = models.SmallIntegerField(verbose_name="Cantidad:")
    rel_precio_compra = models.DecimalField(max_digits=8, decimal_places=2, verbose_name="Precio compra:")
    #rel_precio_venta = models.DecimalField(max_digits=8, decimal_places=2, verbose_name="Precio venta:")
    def _get_costo(self):
        return self.rel_articulo_cantidad*self.rel_precio_compra
    art_total = property(_get_costo)

inventario/forms.py
from dataclasses import field, fields
from pyexpat import model
from socket import fromshare
from django import forms
from django.forms import widgets

from inventario.models import OrdenCompra, Pedidos, TblRelOrdenCompraArticulos, TblRelPedidosArticulos

class OrdenCompraForm(forms.ModelForm):
    class Meta:
        model= OrdenCompra
        exclude = ['ord_estado', 'ord_empleado']
        widgets = {
            'ord_fecha': widgets.DateInput(attrs={'type':'date'})
        }

class TblRelOrdenCompraArticulosForm(forms.ModelForm):
    class Meta:
        model = TblRelOrdenCompraArticulos
        exclude = ['tbl_orden_compras_idorden_compra']

class PedidosComprasForm(forms.ModelForm):
    class Meta:
        model= Pedidos
        exclude = ['ped_estado']
        widgets = {
            'ped_fecha_recivido': widgets.DateInput(attrs={'type':'date'}, format='%Y-%m-%d')
        }

class TblRelPedidosArticulosForm(forms.ModelForm):
    class Meta:
        model= TblRelPedidosArticulos
        exclude = ['tbl_pedidos_idpedido']

main/views.py
from multiprocessing import context
from django.shortcuts import render, redirect
from django.views.defaults import page_not_found
from django.contrib import messages
from django.views.generic import View, TemplateView, ListView, DetailView
from django.contrib.auth.decorators import login_required
from django.contrib.auth import logout
from articulos.models import Articulos, Categoria, Marcas, Proveedores
from inventario.models import Pedidos
from usuarios.models import Ciudades, Cliente, Departamentos, Empleados, OrdenServicio, Servicios, Sucursales, Vehiculo

#from clientes.models import Cliente, Ciudades, Departamentos, Vehiculo

def inicio(request):
    context = {

    }
    return render(request, 'index.html', context)

def nosotros(request):
    titulo = "Nosotros"
    context = {
        'titulo': titulo
    }
    return render(request, 'nosotros.html', context)

def soporte_ayuda(request):
    titulo = "Soporte y ayuda"
    context = {
        'titulo': titulo
    }
    return render(request, 'interfaz_soporte_ayuda.html', context)

def logout_user(request):
    logout(request)
    return redirect('inicio')


@login_required(login_url='login')
def inicioAdmin(request):
    titulo = "Panel Principal"
    context = {
        'titulo': titulo
    }
    return render(request, 'frm_inicio_app.html', context)

# def error_404(request, exception):
#     return page_not_found(request, 'error_404.html')

# class Error_404(TemplateView):
#     template_name = "error_404.html"

class Error404(TemplateView):
    template_name = "error_404.html"

class Error500(TemplateView):
    template_name = "error_500.html"

    @classmethod
    def as_error_view(cls):
        v = cls.as_view()
        def view(request):
            r = v(request)
            r.render()
            return r
        return view

main/templates/inventario/frm_orden_de_compra.html
{% extends 'partials/bodyApp.html' %}
{% load crispy_forms_tags %}
{% load static %}


{% block css %}
<link rel="stylesheet" href="{% static 'css/frm_orden_de_compra.css' %}">
{% endblock css %}
    

{% block contenido %}
<section>
  <div class="titulo_superior">
      <h1>Crear orden de compra</h1>
  </div>
  <div class="form_ordenes">
      <div class="sub_frm_ord">
          <h2>Agregar orden de compra</h2>
      </div>
      
        {% if perms.inventario.add_ordencompra %}     
        <form action="" method="POST" class="form_orden">
        {% csrf_token %}
        {{form|crispy}}
        <input type="hidden" name="modal-status" id="modal-status" value="{{modal_status}}">
        <button class="btn_agregar" name="form-crear">Agregar orden</button>
        </form>
        {% else %}
        <h5 class="control-group text_perms" id="div_id_ord_lugar_emision">Lo sentimos, no cuentas con los permisos para crear una orden de compra.</h5>
        {% endif %}
  </div>
  <div class="contenedor_secundario">
      <div class="titulo_tabla">
          <h2>Órdenes abiertas</h2>
      </div>
      <div class="contenedor_tabla">
          <table>
              <thead>
                  <tr>
                      <th>Empleado responsable</th>
                      <th>Lugar de emisión</th>
                      <th>Proveedor</th>
                      <th>Fecha</th>
                      <th>Término de pago</th>
                      <th>Término de entrega</th>
                      <th>Ótras tarifas</th>
                      <th>Costo estimado</th>        
                      <th>Acciones</th>
                  </tr>
              </thead>
              <tbody>

                  {% for orden in ordenes_compra %}
                  <tr>
                      <td>{{orden.ord_empleado}}</td>
                      <td>{{orden.ord_lugar_emision}}</td>
                      <td>{{orden.ord_proveedor}}</td>
                      <td>{{orden.ord_fecha}}</td>
                      <td>{{orden.ord_termino_pago}}</td>
                      <td>{{orden.ord_termino_entrega}}</td>
                      <td>${{orden.ord_otras_tarifas}}</td>
                      <td>${{orden.ord_costo_estimado}}</td>
                      <td class="d-flex flex-row">
                            {% csrf_token %}
                            <a href="{% url 'detalle_orden_compra' orden.id %}">
                                <img src="{% static 'img/editar.svg' %}" alt="Botón editar" id="btn_editar" title="Editar órden">
                            </a>
                            
                            {% if perms.inventario.change_ordencompra %}
                            <a href="#" onclick="cerrar_orden_compra({{orden.id}})" class="reset">
                                <img src="{% static 'img/finalizar_tarea.svg' %}" class="btn_finalizar_tarea" alt="Cerrar órden" title="Cerrar órden">
                            </a>
                            {% endif %}

                            <a href="{% url 'imprimir_orden_compra' orden.id %}">
                                <img src="{% static 'img/imprimir.svg' %}" alt="Imprimir orden" class="btn_imprimir" title="Imprimir orden">
                            </a>
                      </td>
                  </tr>
                  {% endfor %}

              </tbody>
          </table>
      </div>
  </div>
</section>
{% endblock contenido %}

{% block js %}
<script>
    $(function () {
        $("#sidebarToggle").click();
        $("#id_ord_proveedor").select2({
            placeholder:"Selecciona un proveedor",
            allowClear:true,
            width:"100%",
        });
    });
</script>
{% endblock js %}

main/templates/inventario/frm_pedidos_compras.html
{% extends 'partials/bodyApp.html' %}
{% load crispy_forms_tags %}
{% load static %}


{% block css %}
<link rel="stylesheet" href="{% static 'css/frm_pedidos_compras.css' %}">
{% endblock css %}
    
{% block contenido %}
<section>
  <div class="titulo_superior">
      <h1>Registrar pedidos o compras</h1>
  </div>
  <div class="form_compras">
    <div class="sub_frm_compra">
    <h2>Agregar Compra</h2>
    </div>
      
    {% if perms.inventario.add_pedidos %}     
    <form action="" method="POST" class="form_compra">
        {% csrf_token %}
        {{form|crispy}}
        <input type="hidden" name="modal-status" id="modal-status" value="{{modal_status}}">
        <button class="btn_agregar" name="form-crear">Agregar compra</button>
    </form>
    {% else %}
    <h5 class="control-group text_perms" id="div_id_ped_recivido_por">Lo sentimos, no cuentas con los permisos para agregar un pedido o compra.</h5>
    {% endif %}
  </div>
  <div class="contenedor_secundario">
      <div class="titulo_tabla">
          <h2>Pedidos o compras activas</h2>
      </div>
      <div class="contenedor_tabla">
          <table>
              <thead>
                  <tr>
                      <th>Recibido por:</th>
                      <th>Fecha de recibido</th>
                      <th>Precio total</th>
                      <th>Acciones</th>
                  </tr>
              </thead>
              <tbody>

                  {% for compra in pedidos %}
                  <tr>
                      <td>{{compra.ped_recivido_por}}</td>
                      <td>{{compra.ped_fecha_recivido}}</td>
                      <td>${{compra.ped_precio}}</td>
                      <td class="d-flex flex-row">
                            {% csrf_token %}
                            <a href="{% url 'detalle_compra_pedidos' compra.id %}">
                                <img src="{% static 'img/editar.svg' %}" alt="Botón editar" id="btn_editar" title="Editar compra">
                            </a>
                            
                            {% if perms.inventario.change_pedidos %}                                
                            <a href="#" onclick="cerrar_pedido({{compra.id }})" class="reset">
                                <img src="{% static 'img/finalizar_tarea.svg' %}" class="btn_finalizar_tarea" alt="Cerrar pedido" title="Cerrar pedido">
                            </a>
                            {% endif %}
                      </td>
                  </tr>
                  {% endfor %}

              </tbody>
          </table>
      </div>
  </div>
</section>
{% endblock contenido %}

main/templates/inventario/interfaz_historial_compras.html
{% extends 'partials/bodyApp.html' %}
{% load static %}


{% block css %}
<link rel="stylesheet" href="{% static 'css/historial_de_compras.css' %}">
{% endblock css %}
    

{% block contenido %}
<section>
    <div id="titulo_superior">
        <h1>Historial de compras</h1>
    </div>
    <form method="GET">
        <label for="idbuscar_compra" class="label_buscar_compra">Buscar compra:</label>
        <input type="search" name="com_busqueda" id="idbuscar_compra" value="{{request.GET.com_busqueda}}" placeholder="Buscar">

        <button type="submit" id="btn_mostrar_filtro" class="btn btn-outline-success"><i class="bi bi-search"></i></button>
    </form>
    <div class="container_tabla">
        <table>
            <thead>
                <tr>
                    <th>Fecha</th>
                    <th>Costo total</th>
                    <th>Número pedido</th>
                    <th>Recepcionada por</th>
                    
                    {% if perms.inventario.view_tblrelpedidosarticulos or perms.inventario.delete_pedidos %}           
                    <th>Acciones</th>
                    {% endif %}
                </tr>
            </thead>
            
            {% for historial in pedidos %}            
                <tr>
                    <td>{{historial.ped_fecha_recivido}}</td>
                    <td>${{historial.ped_precio}}</td>
                    <td>{{historial.id}}</td>
                    <td>{{historial.ped_recivido_por}}</td>
                    {% if perms.inventario.view_tblrelpedidosarticulos or perms.inventario.delete_pedidos %}           
                    <td> 
                        
                        {% if perms.inventario.view_tblrelpedidosarticulos %}                            
                        <a href="{% url 'historial_delt_pedido' historial.id %}">
                            <img src="{% static 'img/ver.svg' %}" alt="Botón ver detalles" title="Ver detalles">
                        </a>
                        {% endif %}
                        
                        {% if perms.inventario.delete_pedidos %}                            
                        <a href="#" onclick="eliminar_registros({{historial.id}})">
                            <img src="{% static 'img/eliminar.svg' %}" alt="Botón editar" id="btn_eliminar" title="Mover a papelera">
                        </a>
                        {% endif %}
                    </td>
                    {% endif %}
                </tr>
            {% endfor %}
        </table>
    </div>
    <a href="{% url 'registrar_pedido_compra' %}" id="ancla">
        <img src="{% static 'img/anadir.svg' %}" alt="Icono registrar compra" title="Registrar nueva compra o pedido">
    </a>
</section>
{% endblock contenido %}
    

{% block js %}
    
{% endblock js %}
    

main/templates/inventario/interfaz_historial_dell_ord_compra.html
{% extends 'partials/bodyApp.html' %}
{% load static %}


{% block css %}
<link rel="stylesheet" href="{% static 'css/interfaz_historial_dell_ord_compra.css' %}">
{% endblock css %}
    

{% block contenido %}
<section>
    <div class="titulo_superior">
        <h1>Artículos de la orden de compra</h1>
    </div>
    <h3 class="info1">Estas viendo los artículos que se agrgarón a la orden que seleccionaste</h3>
    <div class="container_tabla">
        <table>
            <thead>
                <tr>
                    <th>Pedido</th>
                    <th>Artículos</th>
                    <th>Cantidad</th>
                    <th>Precio compra</th>
                    <th>Total</th>

                </tr>
            </thead>
            <tbody>
                {% for rel in rel %}
                <tr>
                    <td>{{rel.tbl_orden_compras_idorden_compra}}</td>
                    <td>{{rel.tbl_articulos_idarticulo}}</td>
                    <td>{{rel.rel_cantidad}}</td>
                    <td>${{rel.rel_precio}}</td>
                    <td>${{rel.rel_total}}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</section>
{% endblock contenido %}

main/templates/inventario/rel_orden_compra_articulos.html
{% extends 'partials/bodyApp.html' %}
{% load crispy_forms_tags %}
{% load static %}


{% block css %}
<link rel="stylesheet" href="{% static 'css/rel_orden_compra_articulos.css' %}">
{% endblock css %}


{% block contenido %}
<div class="titulo_superior">
    <h1>Agrega artículos a la orden de compra</h1>
</div>

<div class="form_articulos">
    <div class="sub_articulos">
        <h2>Agregar Artículo</h2>
    </div>
    
    {% if perms.inventario.add_tblrelordencompraarticulos %}
    <form action="" method="POST" class="form1">
        {% csrf_token %}
        {{ form|crispy }}
        <button class="btn_agregar" name="agregar-producto">Agregar Artículo</button>
    </form>
    {% else %}
    <h5 class="control-group text_perms" id="div_id_tbl_articulos_idarticulo">Lo sentimos, no cuentas con los permisos editar esta orden.</h5>
    {% endif %}
</div>
<div class="contenedor_secundario">
    <div class="titulo_tabla">
        <h2>Artículos de la compra o pedido</h2>
    </div>
    <div class="contenedor_tabla">
        <table>
            <thead>
                <tr>
                    <th>Orden</th>
                    <th>Artículos</th>
                    <th>Cantidad</th>
                    <th>Precio estimado</th>
                    <th>Total estimado</th>
                    
                    {% if perms.inventario.delete_tblrelordencompraarticulos %}
                    <th>Acciones</th>
                    {% endif %}
                </tr>
            </thead>
            <tbody>
                {% for rel in rel %}
                <tr>
                    <td>{{rel.tbl_orden_compras_idorden_compra}}</td>
                    <td>{{rel.tbl_articulos_idarticulo}}</td>
                    <td>{{rel.rel_cantidad}}</td>
                    <td>${{rel.rel_precio}}</td>
                    <td>${{rel.rel_total}}</td>
                    {% if perms.inventario.delete_tblrelordencompraarticulos %}
                    <td>
                        <a href="#" onclick="quitar_art_rel_ord_comp_art({{rel.id}})">
                            <img src="{% static 'img/eliminar.svg' %}" alt="Botón eliminar" class="btn_eliminar"
                                title="Quitar artículo">
                        </a>
                    </td>
                    {% endif %}
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>

    {% endblock contenido %}


    {% block js %}
    <!-- {{form.media.js}} -->
    <script>
        $(function () {
            $("#sidebarToggle").click();
            $("#id_tbl_articulos_idarticulo").select2({
                placeholder: "Selecciona un artículo",
                allowClear: true,
                width:"100%",
            });
        });
    </script>
    {% endblock js %}

main/templates/inventario/rel_pedidos_articulos.html
{% extends 'partials/bodyApp.html' %}
{% load crispy_forms_tags %}
{% load static %}


{% block css %}
<link rel="stylesheet" href="{% static 'css/rel_pedido_articulos.css' %}">
{% endblock css %}


{% block contenido %}
<div class="titulo_superior">
    <h1>Agrega artículos a la compra o pedido</h1>
</div>

<div class="form_articulos">
    <div class="sub_articulos">
        <h2>Agregar Artículo</h2>
    </div>
    
    {% if perms.inventario.add_tblrelpedidosarticulos %}     
    <form action="" method="POST" class="form1">
        {% csrf_token %}
        {{ form|crispy }}
        <button class="btn_agregar" name="agregar-producto">Agregar Artículo</button>
    </form>
    {% else %}
    <h5 class="control-group text_perms" id="div_id_rel_articulo_cantidad">Lo sentimos, no cuentas con los permisos para editar este pedio o compra</h5>
    {% endif %}
</div>
<div class="contenedor_secundario">
    <div class="titulo_tabla">
        <h2>Artículos de la compra o pedido</h2>
    </div>
    <div class="contenedor_tabla">
        <table>
            <thead>
                <tr>
                    <th>Pedido</th>
                    <th>Artículos</th>
                    <th>Cantidad</th>
                    <th>Precio compra</th>
                    <th>Total</th>
                    
                    {% if perms.inventario.delete_tblrelpedidosarticulos %}
                    <th>Acciones</th>
                    {% endif %}
                </tr>
            </thead>
            <tbody>
                {% for rel in rel %}
                <tr>
                    <td>{{rel.tbl_pedidos_idpedido}}</td>
                    <td>{{rel.tbl_articulos_idarticulo}}</td>
                    <td>{{rel.rel_articulo_cantidad}}</td>
                    <td>${{rel.rel_precio_compra}}</td>
                    <td>${{rel.art_total}}</td>
                    {% if perms.inventario.delete_tblrelpedidosarticulos %}
                    <td>
                        <a href="#" onclick="quitar_art_rel_pedido_art({{rel.id}})">
                            <img src="{% static 'img/eliminar.svg' %}" alt="Botón eliminar" class="btn_eliminar"
                                title="Quitar artículo">
                        </a>
                    </td>
                    {% endif %}
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>

    {% endblock contenido %}


    {% block js %}
    <!-- {{form.media.js}} -->
    <script>
        $(function () {
            $("#sidebarToggle").click();
            $("#id_tbl_articulos_idarticulo").select2({
                placeholder: "Selecciona un artículo",
                allowClear: true,
                width:"100%",
            });
        });
    </script>
    {% endblock js %}